// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>Fdalilib.ImportClasses</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Fdalilib.ImportClasses
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class AuthData
    {

        private string loginField;

        private string passField;

        public string Login
        {
            get
            {
                return this.loginField;
            }
            set
            {
                this.loginField = value;
            }
        }

        public string Pass
        {
            get
            {
                return this.passField;
            }
            set
            {
                this.passField = value;
            }
        }
    }

    public partial class GetDictionaryContent
    {

        private uint dictionaryCodeField;

        public uint DictionaryCode
        {
            get
            {
                return this.dictionaryCodeField;
            }
            set
            {
                this.dictionaryCodeField = value;
            }
        }
    }

    public partial class Root
    {

        private GetDictionaryContent getDictionaryContentField;

        private AuthData authDataField;

        public Root()
        {
            this.packageDataField = new PackageData();
            this.authDataField = new AuthData();
            //this.getDictionaryContentField = new GetDictionaryContent();
            this.getResultImportApplicationField = new GetResultImportApplication();
            //this.dataForDeleteField = new DataForDelete();
            //this.getResultDeleteApplicationField = new GetResultDeleteApplication();
            //this.getResultCheckApplicationField = new GetResultCheckApplication();
        }

        public GetDictionaryContent GetDictionaryContent
        {
            get
            {
                return this.getDictionaryContentField;
            }
            set
            {
                this.getDictionaryContentField = value;
            }
        }

    }
}
