//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18033
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
    using System.Xml.Serialization;
    using Fdalilib.ImportClasses;

//using Fdalilib.XMLCODE.Applications;
//using Fdalilib.XMLCODE.EntranceCampaignStruct;

// 
// Этот исходный код был создан с помощью xsd, версия=4.0.30319.17929.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class DataForDelete
    {

        private ShortApplication[] applicationsField;

        private ShortApplication[] ordersOfAdmissionField;

        private uint[] competitiveGroupsField;

        private uint[] campaignsField;

        private ulong[] competitiveGroupItemsField;

        private DataForDeleteEntranceTestResults entranceTestResultsField;

        private InstitutionExportsInstitutionExportApplicationApplicationCommonBenefit applicationCommonBenefitsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Application", IsNullable = false)]
        public ShortApplication[] Applications
        {
            get { return this.applicationsField; }
            set { this.applicationsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Application", IsNullable = false)]
        public ShortApplication[] OrdersOfAdmission
        {
            get { return this.ordersOfAdmissionField; }
            set { this.ordersOfAdmissionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CompetitiveGroupID", IsNullable = false)]
        public uint[] CompetitiveGroups
        {
            get { return this.competitiveGroupsField; }
            set { this.competitiveGroupsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CampaignID", IsNullable = false)]
        public uint[] Campaigns
        {
            get { return this.campaignsField; }
            set { this.campaignsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CompetitiveGroupItemID", IsNullable = false)]
        public ulong[] CompetitiveGroupItems
        {
            get { return this.competitiveGroupItemsField; }
            set { this.competitiveGroupItemsField = value; }
        }

        /// <remarks/>
        public DataForDeleteEntranceTestResults EntranceTestResults
        {
            get { return this.entranceTestResultsField; }
            set { this.entranceTestResultsField = value; }
        }

        /// <remarks/>
        public InstitutionExportsInstitutionExportApplicationApplicationCommonBenefit ApplicationCommonBenefits
        {
            get { return this.applicationCommonBenefitsField; }
            set { this.applicationCommonBenefitsField = value; }
        }
    }




