//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18033
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using Fdalilib.XMLCODE.Errors;
using Fdalilib.XMLCODE.Logs;

// 
// Этот исходный код был создан с помощью xsd, версия=4.0.30319.17929.
// 
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ImportResultPackage
    {

        private uint packageIDField;

        private ResultLog logField;

        private ImportResultPackageConflicts conflictsField;

        /// <remarks/>
        public uint PackageID
        {
            get { return this.packageIDField; }
            set { this.packageIDField = value; }
        }

        /// <remarks/>
        public ResultLog Log
        {
            get { return this.logField; }
            set { this.logField = value; }
        }

        /// <remarks/>
        public ImportResultPackageConflicts Conflicts
        {
            get { return this.conflictsField; }
            set { this.conflictsField = value; }
        }
    }




    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TPackageInfo
    {

        private string itemField;

        private PackItemChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PackageException", typeof (string))]
        [System.Xml.Serialization.XmlElementAttribute("PackageNotProcessedYet", typeof (string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public PackItemChoiceType ItemElementName
        {
            get { return this.itemElementNameField; }
            set { this.itemElementNameField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum PackItemChoiceType
    {

        /// <remarks/>
        PackageException,

        /// <remarks/>
        PackageNotProcessedYet,
    }

    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ImportResultPackageConflicts
    {

        private ImportResultPackageConflictsApplication[] applicationsField;

        private ImportResultPackageConflictsApplication1[] ordersOfAdmissionField;

        private uint[] competitiveGroupItemsField;

        private uint[] entranceTestResultsField;

        private ImportResultPackageConflictsApplicationCommonBenefits applicationCommonBenefitsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Application", IsNullable = false)]
        public ImportResultPackageConflictsApplication[] Applications
        {
            get { return this.applicationsField; }
            set { this.applicationsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Application", IsNullable = false)]
        public ImportResultPackageConflictsApplication1[] OrdersOfAdmission
        {
            get { return this.ordersOfAdmissionField; }
            set { this.ordersOfAdmissionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CompetitiveGroupItemID", IsNullable = false)]
        public uint[] CompetitiveGroupItems
        {
            get { return this.competitiveGroupItemsField; }
            set { this.competitiveGroupItemsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("EntranceTestsResultID", IsNullable = false)]
        public uint[] EntranceTestResults
        {
            get { return this.entranceTestResultsField; }
            set { this.entranceTestResultsField = value; }
        }

        /// <remarks/>
        public ImportResultPackageConflictsApplicationCommonBenefits ApplicationCommonBenefits
        {
            get { return this.applicationCommonBenefitsField; }
            set { this.applicationCommonBenefitsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ImportResultPackageConflictsApplication
    {

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        /// <remarks/>
        public string ApplicationNumber
        {
            get { return this.applicationNumberField; }
            set { this.applicationNumberField = value; }
        }

        /// <remarks/>
        public System.DateTime RegistrationDate
        {
            get { return this.registrationDateField; }
            set { this.registrationDateField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ImportResultPackageConflictsApplication1
    {

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        /// <remarks/>
        public string ApplicationNumber
        {
            get { return this.applicationNumberField; }
            set { this.applicationNumberField = value; }
        }

        /// <remarks/>
        public System.DateTime RegistrationDate
        {
            get { return this.registrationDateField; }
            set { this.registrationDateField = value; }
        }
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ImportResultPackageConflictsApplicationCommonBenefits
{

    private uint applicationCommonBenefitIDField;

    /// <remarks/>
    public uint ApplicationCommonBenefitID
    {
        get { return this.applicationCommonBenefitIDField; }
        set { this.applicationCommonBenefitIDField = value; }
    }
}
