//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18033
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;
using Fdalilib.XMLCODE.Applications;

// 
// Этот исходный код был создан с помощью xsd, версия=4.0.30319.17929.
// 

namespace Fdalilib.XMLCODE
{
    public partial class PackageData
    {

        private PackageDataCampaignInfo campaignInfoField;

        private PackageDataAdmissionInfo admissionInfoField;

        private Application[] applicationsField;

        private PackageDataOrderOfAdmission[] ordersOfAdmissionField;

        /// <remarks/>
        /// информация о приемных кампаниях
        public PackageDataCampaignInfo CampaignInfo
        {
            get
            {
                return this.campaignInfoField;
            }
            set
            {
                this.campaignInfoField = value;
            }
        }

        /// <remarks/>
        /// сведения об объеме и структуре приема
        public PackageDataAdmissionInfo AdmissionInfo
        {
            get
            {
                return this.admissionInfoField;
            }
            set
            {
                this.admissionInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Application", IsNullable = false)]
        public Application[] Applications
        {
            get
            {
                return this.applicationsField;
            }
            set
            {
                this.applicationsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OrderOfAdmission", IsNullable = true)]
        public PackageDataOrderOfAdmission[] OrdersOfAdmission
        {
            get
            {
                return this.ordersOfAdmissionField;
            }
            set
            {
                this.ordersOfAdmissionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PackageDataCampaignInfo
    {

        private PackageDataCampaignInfoCampaign[] campaignsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Campaign", IsNullable = false)]
        public PackageDataCampaignInfoCampaign[] Campaigns
        {
            get
            {
                return this.campaignsField;
            }
            set
            {
                this.campaignsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PackageDataCampaignInfoCampaign
    {

        private string uIDField;

        private string nameField;

        private uint yearStartField;

        private uint yearEndField;

        private uint[] educationFormsField;

        private uint statusIDField;

        private PackageDataCampaignInfoCampaignEducationLevel[] educationLevelsField;

        private PackageDataCampaignInfoCampaignCampaignDate[] campaignDatesField;

        /// <remarks/>
        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public uint YearStart
        {
            get
            {
                return this.yearStartField;
            }
            set
            {
                this.yearStartField = value;
            }
        }

        /// <remarks/>
        public uint YearEnd
        {
            get
            {
                return this.yearEndField;
            }
            set
            {
                this.yearEndField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("EducationFormID", IsNullable = false)]
        public uint[] EducationForms
        {
            get
            {
                return this.educationFormsField;
            }
            set
            {
                this.educationFormsField = value;
            }
        }

        /// <remarks/>
        public uint StatusID
        {
            get
            {
                return this.statusIDField;
            }
            set
            {
                this.statusIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("EducationLevel", IsNullable = false)]
        public PackageDataCampaignInfoCampaignEducationLevel[] EducationLevels
        {
            get
            {
                return this.educationLevelsField;
            }
            set
            {
                this.educationLevelsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CampaignDate", IsNullable = false)]
        public PackageDataCampaignInfoCampaignCampaignDate[] CampaignDates
        {
            get
            {
                return this.campaignDatesField;
            }
            set
            {
                this.campaignDatesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PackageDataCampaignInfoCampaignEducationLevel
    {

        private uint courseField;

        private uint educationLevelIDField;

        /// <remarks/>
        public uint Course
        {
            get
            {
                return this.courseField;
            }
            set
            {
                this.courseField = value;
            }
        }

        /// <remarks/>
        public uint EducationLevelID
        {
            get
            {
                return this.educationLevelIDField;
            }
            set
            {
                this.educationLevelIDField = value;
            }
        }
    }

 
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PackageDataCampaignInfoCampaignCampaignDate
    {

        private string uIDField;

        private uint courseField;

        private uint educationLevelIDField;

        private uint educationFormIDField;

        private uint educationSourceIDField;

        private uint stageField;

        private bool stageFieldSpecified;

        private System.DateTime dateStartField;

        private System.DateTime dateEndField;

        private System.DateTime dateOrderField;

        /// <remarks/>
        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }

        /// <remarks/>
        public uint Course
        {
            get
            {
                return this.courseField;
            }
            set
            {
                this.courseField = value;
            }
        }

        /// <remarks/>
        public uint EducationLevelID
        {
            get
            {
                return this.educationLevelIDField;
            }
            set
            {
                this.educationLevelIDField = value;
            }
        }

        /// <remarks/>
        public uint EducationFormID
        {
            get
            {
                return this.educationFormIDField;
            }
            set
            {
                this.educationFormIDField = value;
            }
        }

        /// <remarks/>
        public uint EducationSourceID
        {
            get
            {
                return this.educationSourceIDField;
            }
            set
            {
                this.educationSourceIDField = value;
            }
        }

        public bool ShouldSerializeStage_zach()
        {
            return Stage_zach > 0;
        }

        /// <remarks/>
        [XmlElement(ElementName = "Stage", IsNullable = true)]
        public uint Stage_zach
        {
            get
            {
                return this.stageField;
            }
            set
            {
                this.stageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StageSpecified
        {
            get
            {
                return this.stageFieldSpecified;
            }
            set
            {
                this.stageFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DateStart
        {
            get
            {
                return this.dateStartField;
            }
            set
            {
                this.dateStartField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DateEnd
        {
            get
            {
                return this.dateEndField;
            }
            set
            {
                this.dateEndField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DateOrder
        {
            get
            {
                return this.dateOrderField;
            }
            set
            {
                this.dateOrderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PackageDataAdmissionInfo
    {

        private PackageDataAdmissionInfoItem[] admissionVolumeField;

        private PackageDataAdmissionInfoCompetitiveGroup[] competitiveGroupsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable = false)]
        public PackageDataAdmissionInfoItem[] AdmissionVolume
        {
            get
            {
                return this.admissionVolumeField;
            }
            set
            {
                this.admissionVolumeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CompetitiveGroup", IsNullable = false)]
        public PackageDataAdmissionInfoCompetitiveGroup[] CompetitiveGroups
        {
            get
            {
                return this.competitiveGroupsField;
            }
            set
            {
                this.competitiveGroupsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PackageDataAdmissionInfoItem
    {

        private string uIDField;

        private string campaignUIDField;

        private uint educationLevelIDField;

        private uint courseField;

        private uint directionIDField;

        private uint numberBudgetOField;

        private bool numberBudgetOFieldSpecified;

        private uint numberBudgetOZField;

        private bool numberBudgetOZFieldSpecified;

        private uint numberBudgetZField;

        private bool numberBudgetZFieldSpecified;

        private uint numberPaidOField;

        private bool numberPaidOFieldSpecified;

        private uint numberPaidOZField;

        private bool numberPaidOZFieldSpecified;

        private uint numberPaidZField;

        private bool numberPaidZFieldSpecified;

        private uint numberTargetOField;

        private bool numberTargetOFieldSpecified;

        private uint numberTargetOZField;

        private bool numberTargetOZFieldSpecified;

        private uint numberTargetZField;

        private bool numberTargetZFieldSpecified;

        /// <remarks/>
        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }

        /// <remarks/>
        public string CampaignUID
        {
            get
            {
                return this.campaignUIDField;
            }
            set
            {
                this.campaignUIDField = value;
            }
        }

        /// <remarks/>
        public uint EducationLevelID
        {
            get
            {
                return this.educationLevelIDField;
            }
            set
            {
                this.educationLevelIDField = value;
            }
        }

        /// <remarks/>
        public uint Course
        {
            get
            {
                return this.courseField;
            }
            set
            {
                this.courseField = value;
            }
        }

        /// <remarks/>
        public uint DirectionID
        {
            get
            {
                return this.directionIDField;
            }
            set
            {
                this.directionIDField = value;
            }
        }

        /// <remarks/>
        public uint NumberBudgetO
        {
            get
            {
                return this.numberBudgetOField;
            }
            set
            {
                this.numberBudgetOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberBudgetOSpecified
        {
            get
            {
                return this.numberBudgetOFieldSpecified;
            }
            set
            {
                this.numberBudgetOFieldSpecified = value;
            }
        }

        /// <remarks/>
        public uint NumberBudgetOZ
        {
            get
            {
                return this.numberBudgetOZField;
            }
            set
            {
                this.numberBudgetOZField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberBudgetOZSpecified
        {
            get
            {
                return this.numberBudgetOZFieldSpecified;
            }
            set
            {
                this.numberBudgetOZFieldSpecified = value;
            }
        }

        /// <remarks/>
        public uint NumberBudgetZ
        {
            get
            {
                return this.numberBudgetZField;
            }
            set
            {
                this.numberBudgetZField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberBudgetZSpecified
        {
            get
            {
                return this.numberBudgetZFieldSpecified;
            }
            set
            {
                this.numberBudgetZFieldSpecified = value;
            }
        }

        /// <remarks/>
        public uint NumberPaidO
        {
            get
            {
                return this.numberPaidOField;
            }
            set
            {
                this.numberPaidOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberPaidOSpecified
        {
            get
            {
                return this.numberPaidOFieldSpecified;
            }
            set
            {
                this.numberPaidOFieldSpecified = value;
            }
        }

        /// <remarks/>
        public uint NumberPaidOZ
        {
            get
            {
                return this.numberPaidOZField;
            }
            set
            {
                this.numberPaidOZField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberPaidOZSpecified
        {
            get
            {
                return this.numberPaidOZFieldSpecified;
            }
            set
            {
                this.numberPaidOZFieldSpecified = value;
            }
        }

        /// <remarks/>
        public uint NumberPaidZ
        {
            get
            {
                return this.numberPaidZField;
            }
            set
            {
                this.numberPaidZField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberPaidZSpecified
        {
            get
            {
                return this.numberPaidZFieldSpecified;
            }
            set
            {
                this.numberPaidZFieldSpecified = value;
            }
        }

        /// <remarks/>
        public uint NumberTargetO
        {
            get
            {
                return this.numberTargetOField;
            }
            set
            {
                this.numberTargetOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberTargetOSpecified
        {
            get
            {
                return this.numberTargetOFieldSpecified;
            }
            set
            {
                this.numberTargetOFieldSpecified = value;
            }
        }

        /// <remarks/>
        public uint NumberTargetOZ
        {
            get
            {
                return this.numberTargetOZField;
            }
            set
            {
                this.numberTargetOZField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberTargetOZSpecified
        {
            get
            {
                return this.numberTargetOZFieldSpecified;
            }
            set
            {
                this.numberTargetOZFieldSpecified = value;
            }
        }

        /// <remarks/>
        public uint NumberTargetZ
        {
            get
            {
                return this.numberTargetZField;
            }
            set
            {
                this.numberTargetZField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberTargetZSpecified
        {
            get
            {
                return this.numberTargetZFieldSpecified;
            }
            set
            {
                this.numberTargetZFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PackageDataAdmissionInfoCompetitiveGroup
    {

        private string uIDField;

        private string campaignUIDField;

        private uint courseField;

        private string nameField;

        private PackageDataAdmissionInfoCompetitiveGroupCompetitiveGroupItem[] itemsField;

        private PackageDataAdmissionInfoCompetitiveGroupTargetOrganization[] targetOrganizationsField;

        private PackageDataAdmissionInfoCompetitiveGroupCommonBenefitItem[] commonBenefitField;

        private PackageDataAdmissionInfoCompetitiveGroupEntranceTestItem[] entranceTestItemsField;

        /// <remarks/>
        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }

        /// <remarks/>
        public string CampaignUID
        {
            get
            {
                return this.campaignUIDField;
            }
            set
            {
                this.campaignUIDField = value;
            }
        }

        /// <remarks/>
        public uint Course
        {
            get
            {
                return this.courseField;
            }
            set
            {
                this.courseField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CompetitiveGroupItem", IsNullable = false)]
        public PackageDataAdmissionInfoCompetitiveGroupCompetitiveGroupItem[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("TargetOrganization", IsNullable = false)]
        public PackageDataAdmissionInfoCompetitiveGroupTargetOrganization[] TargetOrganizations
        {
            get
            {
                return this.targetOrganizationsField;
            }
            set
            {
                this.targetOrganizationsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CommonBenefitItem", IsNullable = false)]
        public PackageDataAdmissionInfoCompetitiveGroupCommonBenefitItem[] CommonBenefit
        {
            get
            {
                return this.commonBenefitField;
            }
            set
            {
                this.commonBenefitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("EntranceTestItem", IsNullable = false)]
        public PackageDataAdmissionInfoCompetitiveGroupEntranceTestItem[] EntranceTestItems
        {
            get
            {
                return this.entranceTestItemsField;
            }
            set
            {
                this.entranceTestItemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PackageDataAdmissionInfoCompetitiveGroupCompetitiveGroupItem
    {

        private string uIDField;

        private uint educationLevelIDField;

        private uint directionIDField;

        private uint numberBudgetOField;

        private bool numberBudgetOFieldSpecified;

        private uint numberBudgetOZField;

        private bool numberBudgetOZFieldSpecified;

        private uint numberBudgetZField;

        private bool numberBudgetZFieldSpecified;

        private uint numberPaidOField;

        private bool numberPaidOFieldSpecified;

        private uint numberPaidOZField;

        private bool numberPaidOZFieldSpecified;

        private uint numberPaidZField;

        private bool numberPaidZFieldSpecified;

        /// <remarks/>
        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }

        /// <remarks/>
        public uint EducationLevelID
        {
            get
            {
                return this.educationLevelIDField;
            }
            set
            {
                this.educationLevelIDField = value;
            }
        }

        /// <remarks/>
        public uint DirectionID
        {
            get
            {
                return this.directionIDField;
            }
            set
            {
                this.directionIDField = value;
            }
        }

        /// <remarks/>
        public uint NumberBudgetO
        {
            get
            {
                return this.numberBudgetOField;
            }
            set
            {
                this.numberBudgetOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberBudgetOSpecified
        {
            get
            {
                return this.numberBudgetOFieldSpecified;
            }
            set
            {
                this.numberBudgetOFieldSpecified = value;
            }
        }

        /// <remarks/>
        public uint NumberBudgetOZ
        {
            get
            {
                return this.numberBudgetOZField;
            }
            set
            {
                this.numberBudgetOZField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberBudgetOZSpecified
        {
            get
            {
                return this.numberBudgetOZFieldSpecified;
            }
            set
            {
                this.numberBudgetOZFieldSpecified = value;
            }
        }

        /// <remarks/>
        public uint NumberBudgetZ
        {
            get
            {
                return this.numberBudgetZField;
            }
            set
            {
                this.numberBudgetZField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberBudgetZSpecified
        {
            get
            {
                return this.numberBudgetZFieldSpecified;
            }
            set
            {
                this.numberBudgetZFieldSpecified = value;
            }
        }

        /// <remarks/>
        public uint NumberPaidO
        {
            get
            {
                return this.numberPaidOField;
            }
            set
            {
                this.numberPaidOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberPaidOSpecified
        {
            get
            {
                return this.numberPaidOFieldSpecified;
            }
            set
            {
                this.numberPaidOFieldSpecified = value;
            }
        }

        /// <remarks/>
        public uint NumberPaidOZ
        {
            get
            {
                return this.numberPaidOZField;
            }
            set
            {
                this.numberPaidOZField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberPaidOZSpecified
        {
            get
            {
                return this.numberPaidOZFieldSpecified;
            }
            set
            {
                this.numberPaidOZFieldSpecified = value;
            }
        }

        /// <remarks/>
        public uint NumberPaidZ
        {
            get
            {
                return this.numberPaidZField;
            }
            set
            {
                this.numberPaidZField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberPaidZSpecified
        {
            get
            {
                return this.numberPaidZFieldSpecified;
            }
            set
            {
                this.numberPaidZFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PackageDataAdmissionInfoCompetitiveGroupTargetOrganization
    {

        private string uIDField;

        private string targetOrganizationNameField;

        private PackageDataAdmissionInfoCompetitiveGroupTargetOrganizationCompetitiveGroupTargetItem[] itemsField;

        /// <remarks/>
        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }

        /// <remarks/>
        public string TargetOrganizationName
        {
            get
            {
                return this.targetOrganizationNameField;
            }
            set
            {
                this.targetOrganizationNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CompetitiveGroupTargetItem", IsNullable = false)]
        public PackageDataAdmissionInfoCompetitiveGroupTargetOrganizationCompetitiveGroupTargetItem[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PackageDataAdmissionInfoCompetitiveGroupTargetOrganizationCompetitiveGroupTargetItem
    {

        private string uIDField;

        private uint educationLevelIDField;

        private uint numberTargetOField;

        private bool numberTargetOFieldSpecified;

        private uint numberTargetOZField;

        private bool numberTargetOZFieldSpecified;

        private uint numberTargetZField;

        private bool numberTargetZFieldSpecified;

        private uint directionIDField;

        /// <remarks/>
        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }

        /// <remarks/>
        public uint EducationLevelID
        {
            get
            {
                return this.educationLevelIDField;
            }
            set
            {
                this.educationLevelIDField = value;
            }
        }

        /// <remarks/>
        public uint NumberTargetO
        {
            get
            {
                return this.numberTargetOField;
            }
            set
            {
                this.numberTargetOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberTargetOSpecified
        {
            get
            {
                return this.numberTargetOFieldSpecified;
            }
            set
            {
                this.numberTargetOFieldSpecified = value;
            }
        }

        /// <remarks/>
        public uint NumberTargetOZ
        {
            get
            {
                return this.numberTargetOZField;
            }
            set
            {
                this.numberTargetOZField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberTargetOZSpecified
        {
            get
            {
                return this.numberTargetOZFieldSpecified;
            }
            set
            {
                this.numberTargetOZFieldSpecified = value;
            }
        }

        /// <remarks/>
        public uint NumberTargetZ
        {
            get
            {
                return this.numberTargetZField;
            }
            set
            {
                this.numberTargetZField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberTargetZSpecified
        {
            get
            {
                return this.numberTargetZFieldSpecified;
            }
            set
            {
                this.numberTargetZFieldSpecified = value;
            }
        }

        /// <remarks/>
        public uint DirectionID
        {
            get
            {
                return this.directionIDField;
            }
            set
            {
                this.directionIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PackageDataAdmissionInfoCompetitiveGroupCommonBenefitItem
    {

        private string uIDField;

        private uint[] olympicDiplomTypesField;

        private uint benefitKindIDField;

        private bool isForAllOlympicsField;

        private uint[] olympicsField;

        /// <remarks/>
        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OlympicDiplomTypeID", IsNullable = false)]
        public uint[] OlympicDiplomTypes
        {
            get
            {
                return this.olympicDiplomTypesField;
            }
            set
            {
                this.olympicDiplomTypesField = value;
            }
        }

        /// <remarks/>
        public uint BenefitKindID
        {
            get
            {
                return this.benefitKindIDField;
            }
            set
            {
                this.benefitKindIDField = value;
            }
        }

        /// <remarks/>
        public bool IsForAllOlympics
        {
            get
            {
                return this.isForAllOlympicsField;
            }
            set
            {
                this.isForAllOlympicsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OlympicID", IsNullable = false)]
        public uint[] Olympics
        {
            get
            {
                return this.olympicsField;
            }
            set
            {
                this.olympicsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PackageDataAdmissionInfoCompetitiveGroupEntranceTestItem
    {

        private string uIDField;

        private uint entranceTestTypeIDField;

        private string formField;

        private decimal minScoreField;

        private bool minScoreFieldSpecified;

        private TEntranceTestSubject entranceTestSubjectField;

        private PackageDataAdmissionInfoCompetitiveGroupEntranceTestItemEntranceTestBenefitItem[] entranceTestBenefitsField;

        /// <remarks/>
        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }

        /// <remarks/>
        public uint EntranceTestTypeID
        {
            get
            {
                return this.entranceTestTypeIDField;
            }
            set
            {
                this.entranceTestTypeIDField = value;
            }
        }

        /// <remarks/>
        public string Form
        {
            get
            {
                return this.formField;
            }
            set
            {
                this.formField = value;
            }
        }

        /// <remarks/>
        public decimal MinScore
        {
            get
            {
                return this.minScoreField;
            }
            set
            {
                this.minScoreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinScoreSpecified
        {
            get
            {
                return this.minScoreFieldSpecified;
            }
            set
            {
                this.minScoreFieldSpecified = value;
            }
        }

        /// <remarks/>
        public TEntranceTestSubject EntranceTestSubject
        {
            get
            {
                return this.entranceTestSubjectField;
            }
            set
            {
                this.entranceTestSubjectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("EntranceTestBenefitItem", IsNullable = false)]
        public PackageDataAdmissionInfoCompetitiveGroupEntranceTestItemEntranceTestBenefitItem[] EntranceTestBenefits
        {
            get
            {
                return this.entranceTestBenefitsField;
            }
            set
            {
                this.entranceTestBenefitsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PackageDataAdmissionInfoCompetitiveGroupEntranceTestItemEntranceTestBenefitItem
    {

        private string uIDField;

        private uint[] olympicDiplomTypesField;

        private uint benefitKindIDField;

        private bool isForAllOlympicsField;

        private uint[] olympicsField;

        /// <remarks/>
        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OlympicDiplomTypeID", IsNullable = false)]
        public uint[] OlympicDiplomTypes
        {
            get
            {
                return this.olympicDiplomTypesField;
            }
            set
            {
                this.olympicDiplomTypesField = value;
            }
        }

        /// <remarks/>
        public uint BenefitKindID
        {
            get
            {
                return this.benefitKindIDField;
            }
            set
            {
                this.benefitKindIDField = value;
            }
        }

        /// <remarks/>
        public bool IsForAllOlympics
        {
            get
            {
                return this.isForAllOlympicsField;
            }
            set
            {
                this.isForAllOlympicsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OlympicID", IsNullable = false)]
        public uint[] Olympics
        {
            get
            {
                return this.olympicsField;
            }
            set
            {
                this.olympicsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PackageDataOrderOfAdmission
    {

        private PackageDataOrderOfAdmissionApplication applicationField;

        private uint directionIDField;

        private uint educationFormIDField;

        private uint financeSourceIDField;

        private uint educationLevelIDField;

        private uint stageField;

        private bool stageFieldSpecified;

        private bool isBeneficiaryField;

        private bool isBeneficiaryFieldSpecified;

        /// <remarks/>
        public PackageDataOrderOfAdmissionApplication Application
        {
            get
            {
                return this.applicationField;
            }
            set
            {
                this.applicationField = value;
            }
        }

        /// <remarks/>
        public uint DirectionID
        {
            get
            {
                return this.directionIDField;
            }
            set
            {
                this.directionIDField = value;
            }
        }

        /// <remarks/>
        public uint EducationFormID
        {
            get
            {
                return this.educationFormIDField;
            }
            set
            {
                this.educationFormIDField = value;
            }
        }

        /// <remarks/>
        public uint FinanceSourceID
        {
            get
            {
                return this.financeSourceIDField;
            }
            set
            {
                this.financeSourceIDField = value;
            }
        }

        /// <remarks/>
        public uint EducationLevelID
        {
            get
            {
                return this.educationLevelIDField;
            }
            set
            {
                this.educationLevelIDField = value;
            }
        }

        [XmlElement(ElementName = "Stage")]
        /// <remarks/>
        public uint AdmitionStage
        {
            get
            {
                return this.stageField;
            }
            set
            {
                this.stageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StageSpecified
        {
            get
            {
                return this.stageFieldSpecified;
            }
            set
            {
                this.stageFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool IsBeneficiary
        {
            get
            {
                return this.isBeneficiaryField;
            }
            set
            {
                this.isBeneficiaryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsBeneficiarySpecified
        {
            get
            {
                return this.isBeneficiaryFieldSpecified;
            }
            set
            {
                this.isBeneficiaryFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PackageDataOrderOfAdmissionApplication
    {

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        /// <remarks/>
        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        /// <remarks/>
        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }
}



