//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6400
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

using Fdalilib.XMLCODE;

namespace Fdalilib.XMLCODE
{



    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.3038.
    // 


    /// <remarks/>
    public partial class Root
    {

        private GetDictionaryContent getDictionaryContentField;



        /// <remarks/>
        public GetDictionaryContent GetDictionaryContent
        {
            get { return this.getDictionaryContentField; }
            set { this.getDictionaryContentField = value; }
        }


    }

}