//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18033
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.0.30319.17929.
// 
namespace Fdalilib.XMLCODE
{
    public partial class PackageData
    {

        private PackageDataConsiderListItem[] considerListField;

        private PackageDataRecommendedListItem[] recommendedListField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ConsiderListItem", IsNullable = true)]
        public PackageDataConsiderListItem[] ConsiderList
        {
            get
            {
                return this.considerListField;
            }
            set
            {
                this.considerListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RecommendedListItem", IsNullable = true)]
        public PackageDataRecommendedListItem[] RecommendedList
        {
            get
            {
                return this.recommendedListField;
            }
            set
            {
                this.recommendedListField = value;
            }
        }
    }



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PackageDataConsiderListItem
    {

        private PackageDataConsiderListItemApplication applicationField;

        private uint directionIDField;

        private ushort educationFormIDField;

        private ushort financeSourceIDField;

        private ushort educationLevelIDField;

        /// <remarks/>
        public PackageDataConsiderListItemApplication Application
        {
            get
            {
                return this.applicationField;
            }
            set
            {
                this.applicationField = value;
            }
        }

        /// <remarks/>
        public uint DirectionID
        {
            get
            {
                return this.directionIDField;
            }
            set
            {
                this.directionIDField = value;
            }
        }

        /// <remarks/>
        public ushort EducationFormID
        {
            get
            {
                return this.educationFormIDField;
            }
            set
            {
                this.educationFormIDField = value;
            }
        }

        /// <remarks/>
        public ushort FinanceSourceID
        {
            get
            {
                return this.financeSourceIDField;
            }
            set
            {
                this.financeSourceIDField = value;
            }
        }

        /// <remarks/>
        public ushort EducationLevelID
        {
            get
            {
                return this.educationLevelIDField;
            }
            set
            {
                this.educationLevelIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PackageDataConsiderListItemApplication
    {

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        /// <remarks/>
        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        /// <remarks/>
        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PackageDataRecommendedListItem
    {

        private PackageDataRecommendedListItemApplication applicationField;

        private uint directionIDField;

        private ushort educationFormIDField;

        private ushort financeSourceIDField;

        private ushort educationLevelIDField;

        private ushort stageField;

        private bool stageFieldSpecified;

        /// <remarks/>
        public PackageDataRecommendedListItemApplication Application
        {
            get
            {
                return this.applicationField;
            }
            set
            {
                this.applicationField = value;
            }
        }

        /// <remarks/>
        public uint DirectionID
        {
            get
            {
                return this.directionIDField;
            }
            set
            {
                this.directionIDField = value;
            }
        }

        /// <remarks/>
        public ushort EducationFormID
        {
            get
            {
                return this.educationFormIDField;
            }
            set
            {
                this.educationFormIDField = value;
            }
        }

        /// <remarks/>
        public ushort FinanceSourceID
        {
            get
            {
                return this.financeSourceIDField;
            }
            set
            {
                this.financeSourceIDField = value;
            }
        }

        /// <remarks/>
        public ushort EducationLevelID
        {
            get
            {
                return this.educationLevelIDField;
            }
            set
            {
                this.educationLevelIDField = value;
            }
        }

        /// <remarks/>
        public ushort Stage
        {
            get
            {
                return this.stageField;
            }
            set
            {
                this.stageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StageSpecified
        {
            get
            {
                return this.stageFieldSpecified;
            }
            set
            {
                this.stageFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PackageDataRecommendedListItemApplication
    {

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        /// <remarks/>
        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        /// <remarks/>
        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }
}


