// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>Fdalilib</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Fdalilib.Actions2015

{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class ImportResultPackage
    {

        private ImportResultPackageConflicts conflictsField;

        private ImportResultPackageLog logField;

        private uint packageIDField;

        private uint institutionIDField;

        public ImportResultPackage()
        {
           /* this.logField = new ImportResultPackageLog();
            this.conflictsField = new ImportResultPackageConflicts();*/
        }

        public ImportResultPackageConflicts Conflicts
        {
            get
            {
                return this.conflictsField;
            }
            set
            {
                this.conflictsField = value;
            }
        }

        public ImportResultPackageLog Log
        {
            get
            {
                return this.logField;
            }
            set
            {
                this.logField = value;
            }
        }

        public uint PackageID
        {
            get
            {
                return this.packageIDField;
            }
            set
            {
                this.packageIDField = value;
            }
        }

        public uint InstitutionID
        {
            get
            {
                return this.institutionIDField;
            }
            set
            {
                this.institutionIDField = value;
            }
        }
    }

    public partial class ImportResultPackageConflicts
    {

        private List<ImportResultPackageConflictsApplication> applicationsField;

        private List<ImportResultPackageConflictsApplication1> ordersOfAdmissionField;

        private List<ulong> competitiveGroupItemsField;

        private List<uint> entranceTestResultsField;

        private List<uint> applicationCommonBenefitsField;

        private List<uint> institutionAchievementsField;

        public ImportResultPackageConflicts()
        {
            this.institutionAchievementsField = new List<uint>();
            this.applicationCommonBenefitsField = new List<uint>();
            this.entranceTestResultsField = new List<uint>();
            this.competitiveGroupItemsField = new List<ulong>();
            this.ordersOfAdmissionField = new List<ImportResultPackageConflictsApplication1>();
            this.applicationsField = new List<ImportResultPackageConflictsApplication>();
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Application", IsNullable = false)]
        public List<ImportResultPackageConflictsApplication> Applications
        {
            get
            {
                return this.applicationsField;
            }
            set
            {
                this.applicationsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Application", IsNullable = false)]
        public List<ImportResultPackageConflictsApplication1> OrdersOfAdmission
        {
            get
            {
                return this.ordersOfAdmissionField;
            }
            set
            {
                this.ordersOfAdmissionField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("CompetitiveGroupItemID", IsNullable = false)]
        public List<ulong> CompetitiveGroupItems
        {
            get
            {
                return this.competitiveGroupItemsField;
            }
            set
            {
                this.competitiveGroupItemsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("EntranceTestsResultID", IsNullable = false)]
        public List<uint> EntranceTestResults
        {
            get
            {
                return this.entranceTestResultsField;
            }
            set
            {
                this.entranceTestResultsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("ApplicationCommonBenefitID", IsNullable = false)]
        public List<uint> ApplicationCommonBenefits
        {
            get
            {
                return this.applicationCommonBenefitsField;
            }
            set
            {
                this.applicationCommonBenefitsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("InstitutionAchievementID", IsNullable = false)]
        public List<uint> InstitutionAchievements
        {
            get
            {
                return this.institutionAchievementsField;
            }
            set
            {
                this.institutionAchievementsField = value;
            }
        }
    }

    public partial class ImportResultPackageConflictsApplication
    {

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    public partial class TPackageInfo
    {

        private string itemField;

        private ItemChoiceType itemElementNameField;

        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    public enum ItemChoiceType
    {

        /// <remarks/>
        PackageException,

        /// <remarks/>
        PackageNotProcessedYet,
    }

    public partial class TError
    {

        private string errorCodeField;

        private string errorTextField;

        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }

        public string ErrorText
        {
            get
            {
                return this.errorTextField;
            }
            set
            {
                this.errorTextField = value;
            }
        }
    }

    public partial class TErrorInfo
    {

        private uint errorCodeField;

        private string messageField;

        private TErrorInfoConflictItemsInfo conflictItemsInfoField;

        public TErrorInfo()
        {
            this.conflictItemsInfoField = new TErrorInfoConflictItemsInfo();
        }

        public uint ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }

        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        public TErrorInfoConflictItemsInfo ConflictItemsInfo
        {
            get
            {
                return this.conflictItemsInfoField;
            }
            set
            {
                this.conflictItemsInfoField = value;
            }
        }
    }

    public partial class TErrorInfoConflictItemsInfo
    {

        private List<TErrorInfoConflictItemsInfoApplication> applicationsField;

        private List<TErrorInfoConflictItemsInfoApplication1> ordersOfAdmissionField;

        private TErrorInfoConflictItemsInfoCompetitiveGroupItems competitiveGroupItemsField;

        private TErrorInfoConflictItemsInfoEntranceTestResults entranceTestResultsField;

        private TErrorInfoConflictItemsInfoApplicationCommonBenefits applicationCommonBenefitsField;

        private TErrorInfoConflictItemsInfoInstitutionAchievements institutionAchievementsField;

        public TErrorInfoConflictItemsInfo()
        {
            this.institutionAchievementsField = new TErrorInfoConflictItemsInfoInstitutionAchievements();
            this.applicationCommonBenefitsField = new TErrorInfoConflictItemsInfoApplicationCommonBenefits();
            this.entranceTestResultsField = new TErrorInfoConflictItemsInfoEntranceTestResults();
            this.competitiveGroupItemsField = new TErrorInfoConflictItemsInfoCompetitiveGroupItems();
            this.ordersOfAdmissionField = new List<TErrorInfoConflictItemsInfoApplication1>();
            this.applicationsField = new List<TErrorInfoConflictItemsInfoApplication>();
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Application", IsNullable = false)]
        public List<TErrorInfoConflictItemsInfoApplication> Applications
        {
            get
            {
                return this.applicationsField;
            }
            set
            {
                this.applicationsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Application", IsNullable = false)]
        public List<TErrorInfoConflictItemsInfoApplication1> OrdersOfAdmission
        {
            get
            {
                return this.ordersOfAdmissionField;
            }
            set
            {
                this.ordersOfAdmissionField = value;
            }
        }

        public TErrorInfoConflictItemsInfoCompetitiveGroupItems CompetitiveGroupItems
        {
            get
            {
                return this.competitiveGroupItemsField;
            }
            set
            {
                this.competitiveGroupItemsField = value;
            }
        }

        public TErrorInfoConflictItemsInfoEntranceTestResults EntranceTestResults
        {
            get
            {
                return this.entranceTestResultsField;
            }
            set
            {
                this.entranceTestResultsField = value;
            }
        }

        public TErrorInfoConflictItemsInfoApplicationCommonBenefits ApplicationCommonBenefits
        {
            get
            {
                return this.applicationCommonBenefitsField;
            }
            set
            {
                this.applicationCommonBenefitsField = value;
            }
        }

        public TErrorInfoConflictItemsInfoInstitutionAchievements InstitutionAchievements
        {
            get
            {
                return this.institutionAchievementsField;
            }
            set
            {
                this.institutionAchievementsField = value;
            }
        }
    }

    public partial class TErrorInfoConflictItemsInfoApplication
    {

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        private string uIDField;

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }

        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class TErrorInfoConflictItemsInfoApplication1
    {

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        private string uIDField;

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }

        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class TErrorInfoConflictItemsInfoCompetitiveGroupItems
    {

        private List<uint> competitiveGroupItemIDField;

        private List<string> uIDField;

        public TErrorInfoConflictItemsInfoCompetitiveGroupItems()
        {
            this.uIDField = new List<string>();
            this.competitiveGroupItemIDField = new List<uint>();
        }

        public List<uint> CompetitiveGroupItemID
        {
            get
            {
                return this.competitiveGroupItemIDField;
            }
            set
            {
                this.competitiveGroupItemIDField = value;
            }
        }

        public List<string> UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class TErrorInfoConflictItemsInfoEntranceTestResults
    {

        private List<uint> entranceTestsResultIDField;

        private List<string> uIDField;

        public TErrorInfoConflictItemsInfoEntranceTestResults()
        {
            this.uIDField = new List<string>();
            this.entranceTestsResultIDField = new List<uint>();
        }

        public List<uint> EntranceTestsResultID
        {
            get
            {
                return this.entranceTestsResultIDField;
            }
            set
            {
                this.entranceTestsResultIDField = value;
            }
        }

        public List<string> UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class TErrorInfoConflictItemsInfoApplicationCommonBenefits
    {

        private List<uint> applicationCommonBenefitIDField;

        private List<string> uIDField;

        public TErrorInfoConflictItemsInfoApplicationCommonBenefits()
        {
            this.uIDField = new List<string>();
            this.applicationCommonBenefitIDField = new List<uint>();
        }

        public List<uint> ApplicationCommonBenefitID
        {
            get
            {
                return this.applicationCommonBenefitIDField;
            }
            set
            {
                this.applicationCommonBenefitIDField = value;
            }
        }

        public List<string> UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class TErrorInfoConflictItemsInfoInstitutionAchievements
    {

        private List<uint> institutionAchievementIDField;

        private List<string> uIDField;

        public TErrorInfoConflictItemsInfoInstitutionAchievements()
        {
            this.uIDField = new List<string>();
            this.institutionAchievementIDField = new List<uint>();
        }

        public List<uint> InstitutionAchievementID
        {
            get
            {
                return this.institutionAchievementIDField;
            }
            set
            {
                this.institutionAchievementIDField = value;
            }
        }

        public List<string> UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class ImportResultPackageConflictsApplication1
    {

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    public partial class ImportResultPackageLog
    {

        private ImportResultPackageLogFailed failedField;

        private ImportResultPackageLogSuccessful successfulField;

        public ImportResultPackageLog()
        {
           /* this.successfulField = new ImportResultPackageLogSuccessful();
            this.failedField = new ImportResultPackageLogFailed();*/
        }

        public ImportResultPackageLogFailed Failed
        {
            get
            {
                return this.failedField;
            }
            set
            {
                this.failedField = value;
            }
        }

        public ImportResultPackageLogSuccessful Successful
        {
            get
            {
                return this.successfulField;
            }
            set
            {
                this.successfulField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailed
    {

        private List<ImportResultPackageLogFailedAdmissionVolume> admissionVolumesField;

        private ImportResultPackageLogFailedDistributedAdmissionVolumes distributedAdmissionVolumesField;

        private List<ImportResultPackageLogFailedInstitutionAchievement> institutionAchievementsField;

        private List<ImportResultPackageLogFailedCompetitiveGroup> competitiveGroupsField;

        private List<ImportResultPackageLogFailedCompetitiveGroupItem> competitiveGroupItemsField;

        private List<ImportResultPackageLogFailedTargetOrganization> targetOrganizationsField;

        private List<ImportResultPackageLogFailedTargetOrganizationDirection> targetOrganizationDirectionsField;

        private List<ImportResultPackageLogFailedEntranceTestItem> entranceTestItemsField;

        private List<ImportResultPackageLogFailedCommonBenefitItem> commonBenefitField;

        private List<ImportResultPackageLogFailedEntranceTestBenefitItem> entranceTestBenefitsField;

        private List<ImportResultPackageLogFailedApplication> applicationsField;

        private List<ImportResultPackageLogFailedOlympicDocument> olympicDocumentsField;

        private List<ImportResultPackageLogFailedOlympicTotalDocument> olympicTotalDocumentsField;

        private List<ImportResultPackageLogFailedDisabilityDocument> disabilityDocumentsField;

        private List<ImportResultPackageLogFailedMedicalDocument> medicalDocumentsField;

        private List<ImportResultPackageLogFailedAllowEducationDocument> allowEducationDocumentsField;

        private List<ImportResultPackageLogFailedCustomDocument> customDocumentsField;

        private List<ImportResultPackageLogFailedEntranceTestResult> entranceTestResultsField;

        private List<ImportResultPackageLogFailedApplicationCommonBenefit> applicationCommonBenefitsField;

        private List<Application> ordersOfAdmissionsField;

        private List<ImportResultPackageLogFailedCampaign> campaignsField;

        private List<ImportResultPackageLogFailedCampaignDate> campaignDatesField;

        public ImportResultPackageLogFailed()
        {
           /* this.campaignDatesField = new List<ImportResultPackageLogFailedCampaignDate>();
            this.campaignsField = new List<ImportResultPackageLogFailedCampaign>();
            this.ordersOfAdmissionsField = new ImportResultPackageLogFailedOrdersOfAdmissions();
            this.applicationCommonBenefitsField = new List<ImportResultPackageLogFailedApplicationCommonBenefit>();
            this.entranceTestResultsField = new List<ImportResultPackageLogFailedEntranceTestResult>();
            this.customDocumentsField = new List<ImportResultPackageLogFailedCustomDocument>();
            this.allowEducationDocumentsField = new List<ImportResultPackageLogFailedAllowEducationDocument>();
            this.medicalDocumentsField = new List<ImportResultPackageLogFailedMedicalDocument>();
            this.disabilityDocumentsField = new List<ImportResultPackageLogFailedDisabilityDocument>();
            this.olympicTotalDocumentsField = new List<ImportResultPackageLogFailedOlympicTotalDocument>();
            this.olympicDocumentsField = new List<ImportResultPackageLogFailedOlympicDocument>();
            this.applicationsField = new List<ImportResultPackageLogFailedApplication>();
            this.entranceTestBenefitsField = new List<ImportResultPackageLogFailedEntranceTestBenefitItem>();
            this.commonBenefitField = new List<ImportResultPackageLogFailedCommonBenefitItem>();
            this.entranceTestItemsField = new List<ImportResultPackageLogFailedEntranceTestItem>();
            this.targetOrganizationDirectionsField = new List<ImportResultPackageLogFailedTargetOrganizationDirection>();
            this.targetOrganizationsField = new List<ImportResultPackageLogFailedTargetOrganization>();
            this.competitiveGroupItemsField = new List<ImportResultPackageLogFailedCompetitiveGroupItem>();
            this.competitiveGroupsField = new List<ImportResultPackageLogFailedCompetitiveGroup>();
            this.institutionAchievementsField = new List<ImportResultPackageLogFailedInstitutionAchievement>();
            this.distributedAdmissionVolumesField = new ImportResultPackageLogFailedDistributedAdmissionVolumes();
            this.admissionVolumesField = new List<ImportResultPackageLogFailedAdmissionVolume>();*/
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("AdmissionVolume", IsNullable = false)]
        public List<ImportResultPackageLogFailedAdmissionVolume> AdmissionVolumes
        {
            get
            {
                return this.admissionVolumesField;
            }
            set
            {
                this.admissionVolumesField = value;
            }
        }

        public ImportResultPackageLogFailedDistributedAdmissionVolumes DistributedAdmissionVolumes
        {
            get
            {
                return this.distributedAdmissionVolumesField;
            }
            set
            {
                this.distributedAdmissionVolumesField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("InstitutionAchievement", IsNullable = false)]
        public List<ImportResultPackageLogFailedInstitutionAchievement> InstitutionAchievements
        {
            get
            {
                return this.institutionAchievementsField;
            }
            set
            {
                this.institutionAchievementsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("CompetitiveGroup", IsNullable = false)]
        public List<ImportResultPackageLogFailedCompetitiveGroup> CompetitiveGroups
        {
            get
            {
                return this.competitiveGroupsField;
            }
            set
            {
                this.competitiveGroupsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("CompetitiveGroupItem", IsNullable = false)]
        public List<ImportResultPackageLogFailedCompetitiveGroupItem> CompetitiveGroupItems
        {
            get
            {
                return this.competitiveGroupItemsField;
            }
            set
            {
                this.competitiveGroupItemsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("TargetOrganization", IsNullable = false)]
        public List<ImportResultPackageLogFailedTargetOrganization> TargetOrganizations
        {
            get
            {
                return this.targetOrganizationsField;
            }
            set
            {
                this.targetOrganizationsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("TargetOrganizationDirection", IsNullable = false)]
        public List<ImportResultPackageLogFailedTargetOrganizationDirection> TargetOrganizationDirections
        {
            get
            {
                return this.targetOrganizationDirectionsField;
            }
            set
            {
                this.targetOrganizationDirectionsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("EntranceTestItem", IsNullable = false)]
        public List<ImportResultPackageLogFailedEntranceTestItem> EntranceTestItems
        {
            get
            {
                return this.entranceTestItemsField;
            }
            set
            {
                this.entranceTestItemsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("CommonBenefitItem", IsNullable = false)]
        public List<ImportResultPackageLogFailedCommonBenefitItem> CommonBenefit
        {
            get
            {
                return this.commonBenefitField;
            }
            set
            {
                this.commonBenefitField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("EntranceTestBenefitItem", IsNullable = false)]
        public List<ImportResultPackageLogFailedEntranceTestBenefitItem> EntranceTestBenefits
        {
            get
            {
                return this.entranceTestBenefitsField;
            }
            set
            {
                this.entranceTestBenefitsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Application", IsNullable = false)]
        public List<ImportResultPackageLogFailedApplication> Applications
        {
            get
            {
                return this.applicationsField;
            }
            set
            {
                this.applicationsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("OlympicDocument", IsNullable = false)]
        public List<ImportResultPackageLogFailedOlympicDocument> OlympicDocuments
        {
            get
            {
                return this.olympicDocumentsField;
            }
            set
            {
                this.olympicDocumentsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("OlympicTotalDocument", IsNullable = false)]
        public List<ImportResultPackageLogFailedOlympicTotalDocument> OlympicTotalDocuments
        {
            get
            {
                return this.olympicTotalDocumentsField;
            }
            set
            {
                this.olympicTotalDocumentsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("DisabilityDocument", IsNullable = false)]
        public List<ImportResultPackageLogFailedDisabilityDocument> DisabilityDocuments
        {
            get
            {
                return this.disabilityDocumentsField;
            }
            set
            {
                this.disabilityDocumentsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("MedicalDocument", IsNullable = false)]
        public List<ImportResultPackageLogFailedMedicalDocument> MedicalDocuments
        {
            get
            {
                return this.medicalDocumentsField;
            }
            set
            {
                this.medicalDocumentsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("AllowEducationDocument", IsNullable = false)]
        public List<ImportResultPackageLogFailedAllowEducationDocument> AllowEducationDocuments
        {
            get
            {
                return this.allowEducationDocumentsField;
            }
            set
            {
                this.allowEducationDocumentsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("CustomDocument", IsNullable = false)]
        public List<ImportResultPackageLogFailedCustomDocument> CustomDocuments
        {
            get
            {
                return this.customDocumentsField;
            }
            set
            {
                this.customDocumentsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("EntranceTestResult", IsNullable = false)]
        public List<ImportResultPackageLogFailedEntranceTestResult> EntranceTestResults
        {
            get
            {
                return this.entranceTestResultsField;
            }
            set
            {
                this.entranceTestResultsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("ApplicationCommonBenefit", IsNullable = false)]
        public List<ImportResultPackageLogFailedApplicationCommonBenefit> ApplicationCommonBenefits
        {
            get
            {
                return this.applicationCommonBenefitsField;
            }
            set
            {
                this.applicationCommonBenefitsField = value;
            }
        }

        public List<Application> OrdersOfAdmissions
        {
            get
            {
                return this.ordersOfAdmissionsField;
            }
            set
            {
                this.ordersOfAdmissionsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Campaign", IsNullable = false)]
        public List<ImportResultPackageLogFailedCampaign> Campaigns
        {
            get
            {
                return this.campaignsField;
            }
            set
            {
                this.campaignsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("CampaignDate", IsNullable = false)]
        public List<ImportResultPackageLogFailedCampaignDate> CampaignDates
        {
            get
            {
                return this.campaignDatesField;
            }
            set
            {
                this.campaignDatesField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedAdmissionVolume
    {

        private TErrorInfo errorInfoField;

        private object educationLevelNameField;

        private object directionNameField;

        public ImportResultPackageLogFailedAdmissionVolume()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public object EducationLevelName
        {
            get
            {
                return this.educationLevelNameField;
            }
            set
            {
                this.educationLevelNameField = value;
            }
        }

        public object DirectionName
        {
            get
            {
                return this.directionNameField;
            }
            set
            {
                this.directionNameField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedDistributedAdmissionVolumes
    {

        private ImportResultPackageLogFailedDistributedAdmissionVolumesDistributedAdmissionVolume distributedAdmissionVolumeField;

        public ImportResultPackageLogFailedDistributedAdmissionVolumes()
        {
            this.distributedAdmissionVolumeField = new ImportResultPackageLogFailedDistributedAdmissionVolumesDistributedAdmissionVolume();
        }

        public ImportResultPackageLogFailedDistributedAdmissionVolumesDistributedAdmissionVolume DistributedAdmissionVolume
        {
            get
            {
                return this.distributedAdmissionVolumeField;
            }
            set
            {
                this.distributedAdmissionVolumeField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedDistributedAdmissionVolumesDistributedAdmissionVolume
    {

        private TErrorInfo errorInfoField;

        private string admissionVolumeUIDField;

        private uint levelBudgetField;

        public ImportResultPackageLogFailedDistributedAdmissionVolumesDistributedAdmissionVolume()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string AdmissionVolumeUID
        {
            get
            {
                return this.admissionVolumeUIDField;
            }
            set
            {
                this.admissionVolumeUIDField = value;
            }
        }

        public uint LevelBudget
        {
            get
            {
                return this.levelBudgetField;
            }
            set
            {
                this.levelBudgetField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedInstitutionAchievement
    {

        private TErrorInfo errorInfoField;

        private string iAUIDField;

        private string nameField;

        public ImportResultPackageLogFailedInstitutionAchievement()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string IAUID
        {
            get
            {
                return this.iAUIDField;
            }
            set
            {
                this.iAUIDField = value;
            }
        }

        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedCompetitiveGroup
    {

        private TErrorInfo errorInfoField;

        private string competitiveGroupNameField;

        public ImportResultPackageLogFailedCompetitiveGroup()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string CompetitiveGroupName
        {
            get
            {
                return this.competitiveGroupNameField;
            }
            set
            {
                this.competitiveGroupNameField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedCompetitiveGroupItem
    {

        private TErrorInfo errorInfoField;

        private string directionCodeField;

        private string directionNameField;

        private string competitiveGroupNameField;

        public ImportResultPackageLogFailedCompetitiveGroupItem()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string DirectionCode
        {
            get
            {
                return this.directionCodeField;
            }
            set
            {
                this.directionCodeField = value;
            }
        }

        public string DirectionName
        {
            get
            {
                return this.directionNameField;
            }
            set
            {
                this.directionNameField = value;
            }
        }

        public string CompetitiveGroupName
        {
            get
            {
                return this.competitiveGroupNameField;
            }
            set
            {
                this.competitiveGroupNameField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedTargetOrganization
    {

        private TErrorInfo errorInfoField;

        private string targetOrganizationNameField;

        private string competitiveGroupNameField;

        public ImportResultPackageLogFailedTargetOrganization()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string TargetOrganizationName
        {
            get
            {
                return this.targetOrganizationNameField;
            }
            set
            {
                this.targetOrganizationNameField = value;
            }
        }

        public string CompetitiveGroupName
        {
            get
            {
                return this.competitiveGroupNameField;
            }
            set
            {
                this.competitiveGroupNameField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedTargetOrganizationDirection
    {

        private TErrorInfo errorInfoField;

        private string directionNameField;

        private string educationLevelNameField;

        private string targetOrganizationNameField;

        private string competitiveGroupNameField;

        public ImportResultPackageLogFailedTargetOrganizationDirection()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string DirectionName
        {
            get
            {
                return this.directionNameField;
            }
            set
            {
                this.directionNameField = value;
            }
        }

        public string EducationLevelName
        {
            get
            {
                return this.educationLevelNameField;
            }
            set
            {
                this.educationLevelNameField = value;
            }
        }

        public string TargetOrganizationName
        {
            get
            {
                return this.targetOrganizationNameField;
            }
            set
            {
                this.targetOrganizationNameField = value;
            }
        }

        public string CompetitiveGroupName
        {
            get
            {
                return this.competitiveGroupNameField;
            }
            set
            {
                this.competitiveGroupNameField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedEntranceTestItem
    {

        private TErrorInfo errorInfoField;

        private string entranceTestTypeField;

        private string subjectNameField;

        private string competitiveGroupNameField;

        public ImportResultPackageLogFailedEntranceTestItem()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string EntranceTestType
        {
            get
            {
                return this.entranceTestTypeField;
            }
            set
            {
                this.entranceTestTypeField = value;
            }
        }

        public string SubjectName
        {
            get
            {
                return this.subjectNameField;
            }
            set
            {
                this.subjectNameField = value;
            }
        }

        public string CompetitiveGroupName
        {
            get
            {
                return this.competitiveGroupNameField;
            }
            set
            {
                this.competitiveGroupNameField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedCommonBenefitItem
    {

        private TErrorInfo errorInfoField;

        private string benefitKindNameField;

        private string competitiveGroupNameField;

        public ImportResultPackageLogFailedCommonBenefitItem()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string BenefitKindName
        {
            get
            {
                return this.benefitKindNameField;
            }
            set
            {
                this.benefitKindNameField = value;
            }
        }

        public string CompetitiveGroupName
        {
            get
            {
                return this.competitiveGroupNameField;
            }
            set
            {
                this.competitiveGroupNameField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedEntranceTestBenefitItem
    {

        private TErrorInfo errorInfoField;

        private string benefitKindNameField;

        private string entranceTestTypeField;

        private string subjectNameField;

        private string competitiveGroupNameField;

        public ImportResultPackageLogFailedEntranceTestBenefitItem()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string BenefitKindName
        {
            get
            {
                return this.benefitKindNameField;
            }
            set
            {
                this.benefitKindNameField = value;
            }
        }

        public string EntranceTestType
        {
            get
            {
                return this.entranceTestTypeField;
            }
            set
            {
                this.entranceTestTypeField = value;
            }
        }

        public string SubjectName
        {
            get
            {
                return this.subjectNameField;
            }
            set
            {
                this.subjectNameField = value;
            }
        }

        public string CompetitiveGroupName
        {
            get
            {
                return this.competitiveGroupNameField;
            }
            set
            {
                this.competitiveGroupNameField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedApplication
    {

        private TErrorInfo errorInfoField;

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        public ImportResultPackageLogFailedApplication()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedOlympicDocument
    {

        private TErrorInfo errorInfoField;

        private string documentNumberField;

        private System.DateTime documentDateField;

        private bool documentDateFieldSpecified;

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        public ImportResultPackageLogFailedOlympicDocument()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string DocumentNumber
        {
            get
            {
                return this.documentNumberField;
            }
            set
            {
                this.documentNumberField = value;
            }
        }

        public System.DateTime DocumentDate
        {
            get
            {
                return this.documentDateField;
            }
            set
            {
                this.documentDateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentDateSpecified
        {
            get
            {
                return this.documentDateFieldSpecified;
            }
            set
            {
                this.documentDateFieldSpecified = value;
            }
        }

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedOlympicTotalDocument
    {

        private TErrorInfo errorInfoField;

        private string documentNumberField;

        private System.DateTime documentDateField;

        private bool documentDateFieldSpecified;

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        public ImportResultPackageLogFailedOlympicTotalDocument()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string DocumentNumber
        {
            get
            {
                return this.documentNumberField;
            }
            set
            {
                this.documentNumberField = value;
            }
        }

        public System.DateTime DocumentDate
        {
            get
            {
                return this.documentDateField;
            }
            set
            {
                this.documentDateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentDateSpecified
        {
            get
            {
                return this.documentDateFieldSpecified;
            }
            set
            {
                this.documentDateFieldSpecified = value;
            }
        }

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedDisabilityDocument
    {

        private TErrorInfo errorInfoField;

        private string documentNumberField;

        private System.DateTime documentDateField;

        private bool documentDateFieldSpecified;

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        public ImportResultPackageLogFailedDisabilityDocument()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string DocumentNumber
        {
            get
            {
                return this.documentNumberField;
            }
            set
            {
                this.documentNumberField = value;
            }
        }

        public System.DateTime DocumentDate
        {
            get
            {
                return this.documentDateField;
            }
            set
            {
                this.documentDateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentDateSpecified
        {
            get
            {
                return this.documentDateFieldSpecified;
            }
            set
            {
                this.documentDateFieldSpecified = value;
            }
        }

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedMedicalDocument
    {

        private TErrorInfo errorInfoField;

        private string documentNumberField;

        private System.DateTime documentDateField;

        private bool documentDateFieldSpecified;

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        public ImportResultPackageLogFailedMedicalDocument()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string DocumentNumber
        {
            get
            {
                return this.documentNumberField;
            }
            set
            {
                this.documentNumberField = value;
            }
        }

        public System.DateTime DocumentDate
        {
            get
            {
                return this.documentDateField;
            }
            set
            {
                this.documentDateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentDateSpecified
        {
            get
            {
                return this.documentDateFieldSpecified;
            }
            set
            {
                this.documentDateFieldSpecified = value;
            }
        }

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedAllowEducationDocument
    {

        private TErrorInfo errorInfoField;

        private string documentNumberField;

        private System.DateTime documentDateField;

        private bool documentDateFieldSpecified;

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        public ImportResultPackageLogFailedAllowEducationDocument()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string DocumentNumber
        {
            get
            {
                return this.documentNumberField;
            }
            set
            {
                this.documentNumberField = value;
            }
        }

        public System.DateTime DocumentDate
        {
            get
            {
                return this.documentDateField;
            }
            set
            {
                this.documentDateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentDateSpecified
        {
            get
            {
                return this.documentDateFieldSpecified;
            }
            set
            {
                this.documentDateFieldSpecified = value;
            }
        }

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedCustomDocument
    {

        private TErrorInfo errorInfoField;

        private string documentNumberField;

        private System.DateTime documentDateField;

        private bool documentDateFieldSpecified;

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        public ImportResultPackageLogFailedCustomDocument()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string DocumentNumber
        {
            get
            {
                return this.documentNumberField;
            }
            set
            {
                this.documentNumberField = value;
            }
        }

        public System.DateTime DocumentDate
        {
            get
            {
                return this.documentDateField;
            }
            set
            {
                this.documentDateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentDateSpecified
        {
            get
            {
                return this.documentDateFieldSpecified;
            }
            set
            {
                this.documentDateFieldSpecified = value;
            }
        }

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedEntranceTestResult
    {

        private TErrorInfo errorInfoField;

        private string resultSourceTypeField;

        private string subjectNameField;

        private decimal resultValueField;

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        public ImportResultPackageLogFailedEntranceTestResult()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string ResultSourceType
        {
            get
            {
                return this.resultSourceTypeField;
            }
            set
            {
                this.resultSourceTypeField = value;
            }
        }

        public string SubjectName
        {
            get
            {
                return this.subjectNameField;
            }
            set
            {
                this.subjectNameField = value;
            }
        }

        public decimal ResultValue
        {
            get
            {
                return this.resultValueField;
            }
            set
            {
                this.resultValueField = value;
            }
        }

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedApplicationCommonBenefit
    {

        private TErrorInfo errorInfoField;

        private string benefitKindNameField;

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        public ImportResultPackageLogFailedApplicationCommonBenefit()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string BenefitKindName
        {
            get
            {
                return this.benefitKindNameField;
            }
            set
            {
                this.benefitKindNameField = value;
            }
        }

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedOrdersOfAdmissions
    {

        private List<Application> applicationField;

        private List<ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmission> orderOfAdmissionField;

        public ImportResultPackageLogFailedOrdersOfAdmissions()
        {
            /*this.orderOfAdmissionField = new List<ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmission>();
            this.applicationField = new List<ImportResultPackageLogFailedOrdersOfAdmissionsApplication>();*/
        }

        public List<Application> Application
        {
            get
            {
                return this.applicationField;
            }
            set
            {
                this.applicationField = value;
            }
        }

        public List<ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmission> OrderOfAdmission
        {
            get
            {
                return this.orderOfAdmissionField;
            }
            set
            {
                this.orderOfAdmissionField = value;
            }
        }
    }

    public partial class Application
    {

        private ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfo errorInfoField;

        public ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfo
    {

        private uint errorCodeField;

        private string messageField;

        private ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfo conflictItemsInfoField;

        private string orderOfAdmissionUIDField;

        private string orderNameField;

        private string orderNumberField;

        private System.DateTime orderDateField;

        public ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfo()
        {
            this.conflictItemsInfoField = new ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfo();
        }

        public uint ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }

        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        public ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfo ConflictItemsInfo
        {
            get
            {
                return this.conflictItemsInfoField;
            }
            set
            {
                this.conflictItemsInfoField = value;
            }
        }

        public string OrderOfAdmissionUID
        {
            get
            {
                return this.orderOfAdmissionUIDField;
            }
            set
            {
                this.orderOfAdmissionUIDField = value;
            }
        }

        public string OrderName
        {
            get
            {
                return this.orderNameField;
            }
            set
            {
                this.orderNameField = value;
            }
        }

        public string OrderNumber
        {
            get
            {
                return this.orderNumberField;
            }
            set
            {
                this.orderNumberField = value;
            }
        }

        public System.DateTime OrderDate
        {
            get
            {
                return this.orderDateField;
            }
            set
            {
                this.orderDateField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfo
    {

        private List<ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoApplication> applicationsField;

        private ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoOrdersOfAdmission ordersOfAdmissionField;

        private ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoCompetitiveGroupItems competitiveGroupItemsField;

        private ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoEntranceTestResults entranceTestResultsField;

        private ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoApplicationCommonBenefits applicationCommonBenefitsField;

        public ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfo()
        {
            this.applicationCommonBenefitsField = new ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoApplicationCommonBenefits();
            this.entranceTestResultsField = new ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoEntranceTestResults();
            this.competitiveGroupItemsField = new ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoCompetitiveGroupItems();
            this.ordersOfAdmissionField = new ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoOrdersOfAdmission();
            this.applicationsField = new List<ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoApplication>();
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Application", IsNullable = false)]
        public List<ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoApplication> Applications
        {
            get
            {
                return this.applicationsField;
            }
            set
            {
                this.applicationsField = value;
            }
        }

        public ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoOrdersOfAdmission OrdersOfAdmission
        {
            get
            {
                return this.ordersOfAdmissionField;
            }
            set
            {
                this.ordersOfAdmissionField = value;
            }
        }

        public ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoCompetitiveGroupItems CompetitiveGroupItems
        {
            get
            {
                return this.competitiveGroupItemsField;
            }
            set
            {
                this.competitiveGroupItemsField = value;
            }
        }

        public ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoEntranceTestResults EntranceTestResults
        {
            get
            {
                return this.entranceTestResultsField;
            }
            set
            {
                this.entranceTestResultsField = value;
            }
        }

        public ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoApplicationCommonBenefits ApplicationCommonBenefits
        {
            get
            {
                return this.applicationCommonBenefitsField;
            }
            set
            {
                this.applicationCommonBenefitsField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoApplication
    {

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        private string uIDField;

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }

        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoOrdersOfAdmission
    {

        private List<ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoOrdersOfAdmissionApplication> applicationField;

        private List<ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoOrdersOfAdmissionOrderOfAdmission> orderOfAdmissionField;

        public ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoOrdersOfAdmission()
        {
            this.orderOfAdmissionField = new List<ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoOrdersOfAdmissionOrderOfAdmission>();
            this.applicationField = new List<ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoOrdersOfAdmissionApplication>();
        }

        public List<ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoOrdersOfAdmissionApplication> Application
        {
            get
            {
                return this.applicationField;
            }
            set
            {
                this.applicationField = value;
            }
        }

        public List<ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoOrdersOfAdmissionOrderOfAdmission> OrderOfAdmission
        {
            get
            {
                return this.orderOfAdmissionField;
            }
            set
            {
                this.orderOfAdmissionField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoOrdersOfAdmissionApplication
    {

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        private string uIDField;

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }

        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoOrdersOfAdmissionOrderOfAdmission
    {

        private string orderNameField;

        private string orderNumberField;

        private System.DateTime orderDateField;

        public string OrderName
        {
            get
            {
                return this.orderNameField;
            }
            set
            {
                this.orderNameField = value;
            }
        }

        public string OrderNumber
        {
            get
            {
                return this.orderNumberField;
            }
            set
            {
                this.orderNumberField = value;
            }
        }

        public System.DateTime OrderDate
        {
            get
            {
                return this.orderDateField;
            }
            set
            {
                this.orderDateField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoCompetitiveGroupItems
    {

        private List<uint> competitiveGroupItemIDField;

        private List<string> uIDField;

        public ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoCompetitiveGroupItems()
        {
            this.uIDField = new List<string>();
            this.competitiveGroupItemIDField = new List<uint>();
        }

        public List<uint> CompetitiveGroupItemID
        {
            get
            {
                return this.competitiveGroupItemIDField;
            }
            set
            {
                this.competitiveGroupItemIDField = value;
            }
        }

        public List<string> UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoEntranceTestResults
    {

        private List<uint> entranceTestsResultIDField;

        private List<string> uIDField;

        public ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoEntranceTestResults()
        {
            this.uIDField = new List<string>();
            this.entranceTestsResultIDField = new List<uint>();
        }

        public List<uint> EntranceTestsResultID
        {
            get
            {
                return this.entranceTestsResultIDField;
            }
            set
            {
                this.entranceTestsResultIDField = value;
            }
        }

        public List<string> UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoApplicationCommonBenefits
    {

        private List<uint> applicationCommonBenefitIDField;

        private List<string> uIDField;

        public ImportResultPackageLogFailedOrdersOfAdmissionsApplicationErrorInfoConflictItemsInfoApplicationCommonBenefits()
        {
            this.uIDField = new List<string>();
            this.applicationCommonBenefitIDField = new List<uint>();
        }

        public List<uint> ApplicationCommonBenefitID
        {
            get
            {
                return this.applicationCommonBenefitIDField;
            }
            set
            {
                this.applicationCommonBenefitIDField = value;
            }
        }

        public List<string> UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmission
    {

        private ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfo errorInfoField;

        private string orderOfAdmissionUIDField;

        private string orderNameField;

        private uint orderNumberField;

        private System.DateTime orderDateField;

        public ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmission()
        {
            this.errorInfoField = new ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfo();
        }

        public ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string OrderOfAdmissionUID
        {
            get
            {
                return this.orderOfAdmissionUIDField;
            }
            set
            {
                this.orderOfAdmissionUIDField = value;
            }
        }

        public string OrderName
        {
            get
            {
                return this.orderNameField;
            }
            set
            {
                this.orderNameField = value;
            }
        }

        public uint OrderNumber
        {
            get
            {
                return this.orderNumberField;
            }
            set
            {
                this.orderNumberField = value;
            }
        }

        public System.DateTime OrderDate
        {
            get
            {
                return this.orderDateField;
            }
            set
            {
                this.orderDateField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfo
    {

        private uint errorCodeField;

        private string messageField;

        private ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfo conflictItemsInfoField;

        private string orderOfAdmissionUIDField;

        private string orderNameField;

        private string orderNumberField;

        private System.DateTime orderDateField;

        public ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfo()
        {
            this.conflictItemsInfoField = new ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfo();
        }

        public uint ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }

        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        public ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfo ConflictItemsInfo
        {
            get
            {
                return this.conflictItemsInfoField;
            }
            set
            {
                this.conflictItemsInfoField = value;
            }
        }

        public string OrderOfAdmissionUID
        {
            get
            {
                return this.orderOfAdmissionUIDField;
            }
            set
            {
                this.orderOfAdmissionUIDField = value;
            }
        }

        public string OrderName
        {
            get
            {
                return this.orderNameField;
            }
            set
            {
                this.orderNameField = value;
            }
        }

        public string OrderNumber
        {
            get
            {
                return this.orderNumberField;
            }
            set
            {
                this.orderNumberField = value;
            }
        }

        public System.DateTime OrderDate
        {
            get
            {
                return this.orderDateField;
            }
            set
            {
                this.orderDateField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfo
    {

        private List<ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoApplication> applicationsField;

        private ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoOrdersOfAdmission ordersOfAdmissionField;

        private ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoCompetitiveGroupItems competitiveGroupItemsField;

        private ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoEntranceTestResults entranceTestResultsField;

        private ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoApplicationCommonBenefits applicationCommonBenefitsField;

        public ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfo()
        {
            this.applicationCommonBenefitsField = new ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoApplicationCommonBenefits();
            this.entranceTestResultsField = new ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoEntranceTestResults();
            this.competitiveGroupItemsField = new ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoCompetitiveGroupItems();
            this.ordersOfAdmissionField = new ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoOrdersOfAdmission();
            this.applicationsField = new List<ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoApplication>();
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Application", IsNullable = false)]
        public List<ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoApplication> Applications
        {
            get
            {
                return this.applicationsField;
            }
            set
            {
                this.applicationsField = value;
            }
        }

        public ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoOrdersOfAdmission OrdersOfAdmission
        {
            get
            {
                return this.ordersOfAdmissionField;
            }
            set
            {
                this.ordersOfAdmissionField = value;
            }
        }

        public ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoCompetitiveGroupItems CompetitiveGroupItems
        {
            get
            {
                return this.competitiveGroupItemsField;
            }
            set
            {
                this.competitiveGroupItemsField = value;
            }
        }

        public ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoEntranceTestResults EntranceTestResults
        {
            get
            {
                return this.entranceTestResultsField;
            }
            set
            {
                this.entranceTestResultsField = value;
            }
        }

        public ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoApplicationCommonBenefits ApplicationCommonBenefits
        {
            get
            {
                return this.applicationCommonBenefitsField;
            }
            set
            {
                this.applicationCommonBenefitsField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoApplication
    {

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        private string uIDField;

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }

        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoOrdersOfAdmission
    {

        private List<ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoOrdersOfAdmissionApplication> applicationField;

        private List<ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoOrdersOfAdmissionOrderOfAdmission> orderOfAdmissionField;

        public ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoOrdersOfAdmission()
        {
            this.orderOfAdmissionField = new List<ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoOrdersOfAdmissionOrderOfAdmission>();
            this.applicationField = new List<ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoOrdersOfAdmissionApplication>();
        }

        public List<ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoOrdersOfAdmissionApplication> Application
        {
            get
            {
                return this.applicationField;
            }
            set
            {
                this.applicationField = value;
            }
        }

        public List<ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoOrdersOfAdmissionOrderOfAdmission> OrderOfAdmission
        {
            get
            {
                return this.orderOfAdmissionField;
            }
            set
            {
                this.orderOfAdmissionField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoOrdersOfAdmissionApplication
    {

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        private string uIDField;

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }

        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoOrdersOfAdmissionOrderOfAdmission
    {

        private string orderNameField;

        private string orderNumberField;

        private System.DateTime orderDateField;

        public string OrderName
        {
            get
            {
                return this.orderNameField;
            }
            set
            {
                this.orderNameField = value;
            }
        }

        public string OrderNumber
        {
            get
            {
                return this.orderNumberField;
            }
            set
            {
                this.orderNumberField = value;
            }
        }

        public System.DateTime OrderDate
        {
            get
            {
                return this.orderDateField;
            }
            set
            {
                this.orderDateField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoCompetitiveGroupItems
    {

        private List<uint> competitiveGroupItemIDField;

        private List<string> uIDField;

        public ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoCompetitiveGroupItems()
        {
            this.uIDField = new List<string>();
            this.competitiveGroupItemIDField = new List<uint>();
        }

        public List<uint> CompetitiveGroupItemID
        {
            get
            {
                return this.competitiveGroupItemIDField;
            }
            set
            {
                this.competitiveGroupItemIDField = value;
            }
        }

        public List<string> UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoEntranceTestResults
    {

        private List<uint> entranceTestsResultIDField;

        private List<string> uIDField;

        public ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoEntranceTestResults()
        {
            this.uIDField = new List<string>();
            this.entranceTestsResultIDField = new List<uint>();
        }

        public List<uint> EntranceTestsResultID
        {
            get
            {
                return this.entranceTestsResultIDField;
            }
            set
            {
                this.entranceTestsResultIDField = value;
            }
        }

        public List<string> UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoApplicationCommonBenefits
    {

        private List<uint> applicationCommonBenefitIDField;

        private List<string> uIDField;

        public ImportResultPackageLogFailedOrdersOfAdmissionsOrderOfAdmissionErrorInfoConflictItemsInfoApplicationCommonBenefits()
        {
            this.uIDField = new List<string>();
            this.applicationCommonBenefitIDField = new List<uint>();
        }

        public List<uint> ApplicationCommonBenefitID
        {
            get
            {
                return this.applicationCommonBenefitIDField;
            }
            set
            {
                this.applicationCommonBenefitIDField = value;
            }
        }

        public List<string> UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedCampaign
    {

        private TErrorInfo errorInfoField;

        private string nameField;

        public ImportResultPackageLogFailedCampaign()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    public partial class ImportResultPackageLogFailedCampaignDate
    {

        private TErrorInfo errorInfoField;

        private string uIDField;

        public ImportResultPackageLogFailedCampaignDate()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class ImportResultPackageLogSuccessful
    {

        private uint admissionVolumesField;

        private uint distributedAdmissionVolumesField;

        private uint institutionAchievementsField;

        private uint applicationsField;

        private uint campaignsField;

        private uint competitiveGroupItemsField;

        private byte competitiveGroupsField;

        private byte consideredApplicationsField;

        private uint ordersOfAdmissionsField;

        private byte recommendedApplicationsField;

        private byte recommendedListsField;

        public uint AdmissionVolumes
        {
            get
            {
                return this.admissionVolumesField;
            }
            set
            {
                this.admissionVolumesField = value;
            }
        }

        public uint DistributedAdmissionVolumes
        {
            get
            {
                return this.distributedAdmissionVolumesField;
            }
            set
            {
                this.distributedAdmissionVolumesField = value;
            }
        }

        public uint InstitutionAchievements
        {
            get
            {
                return this.institutionAchievementsField;
            }
            set
            {
                this.institutionAchievementsField = value;
            }
        }

        public uint Applications
        {
            get
            {
                return this.applicationsField;
            }
            set
            {
                this.applicationsField = value;
            }
        }

        public uint Campaigns
        {
            get
            {
                return this.campaignsField;
            }
            set
            {
                this.campaignsField = value;
            }
        }

        public uint CompetitiveGroupItems
        {
            get
            {
                return this.competitiveGroupItemsField;
            }
            set
            {
                this.competitiveGroupItemsField = value;
            }
        }

        public byte CompetitiveGroups
        {
            get
            {
                return this.competitiveGroupsField;
            }
            set
            {
                this.competitiveGroupsField = value;
            }
        }

        public byte ConsideredApplications
        {
            get
            {
                return this.consideredApplicationsField;
            }
            set
            {
                this.consideredApplicationsField = value;
            }
        }

        public uint OrdersOfAdmissions
        {
            get
            {
                return this.ordersOfAdmissionsField;
            }
            set
            {
                this.ordersOfAdmissionsField = value;
            }
        }

        public byte RecommendedApplications
        {
            get
            {
                return this.recommendedApplicationsField;
            }
            set
            {
                this.recommendedApplicationsField = value;
            }
        }

        public byte RecommendedLists
        {
            get
            {
                return this.recommendedListsField;
            }
            set
            {
                this.recommendedListsField = value;
            }
        }
    }
}
