// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>Fdalilib</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Fdalilib.Actions2015
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class DataForDelete
    {

        private List<DataForDeleteApplication> applicationsField;

        private List<Application> ordersOfAdmissionField;

        private DataForDeleteCompetitiveGroups competitiveGroupsField;

        private DataForDeleteCampaigns campaignsField;

        private List<string> institutionAchievementsField;

        private DataForDeleteCompetitiveGroupItems competitiveGroupItemsField;

        private DataForDeleteEntranceTestResults entranceTestResultsField;

        private DataForDeleteApplicationCommonBenefits applicationCommonBenefitsField;

        private List<DataForDeleteRecommendedList> recommendedListsField;

        public DataForDelete()
        {
         /*   this.recommendedListsField = new List<DataForDeleteRecommendedList>();
            this.applicationCommonBenefitsField = new DataForDeleteApplicationCommonBenefits();
            this.entranceTestResultsField = new DataForDeleteEntranceTestResults();
            this.competitiveGroupItemsField = new DataForDeleteCompetitiveGroupItems();
            this.institutionAchievementsField = new List<string>();
            this.campaignsField = new DataForDeleteCampaigns();
            this.competitiveGroupsField = new DataForDeleteCompetitiveGroups();
            this.ordersOfAdmissionField = new DataForDeleteOrdersOfAdmission();
            this.applicationsField = new List<DataForDeleteApplication>();*/
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Application", IsNullable = false)]
        public List<DataForDeleteApplication> Applications
        {
            get
            {
                return this.applicationsField;
            }
            set
            {
                this.applicationsField = value;
            }
        }

        public List<Application> OrdersOfAdmission
        {
            get
            {
                return this.ordersOfAdmissionField;
            }
            set
            {
                this.ordersOfAdmissionField = value;
            }
        }

        public DataForDeleteCompetitiveGroups CompetitiveGroups
        {
            get
            {
                return this.competitiveGroupsField;
            }
            set
            {
                this.competitiveGroupsField = value;
            }
        }

        public DataForDeleteCampaigns Campaigns
        {
            get
            {
                return this.campaignsField;
            }
            set
            {
                this.campaignsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("InstitutionAchievementUID", IsNullable = false)]
        public List<string> InstitutionAchievements
        {
            get
            {
                return this.institutionAchievementsField;
            }
            set
            {
                this.institutionAchievementsField = value;
            }
        }

        public DataForDeleteCompetitiveGroupItems CompetitiveGroupItems
        {
            get
            {
                return this.competitiveGroupItemsField;
            }
            set
            {
                this.competitiveGroupItemsField = value;
            }
        }

        public DataForDeleteEntranceTestResults EntranceTestResults
        {
            get
            {
                return this.entranceTestResultsField;
            }
            set
            {
                this.entranceTestResultsField = value;
            }
        }

        public DataForDeleteApplicationCommonBenefits ApplicationCommonBenefits
        {
            get
            {
                return this.applicationCommonBenefitsField;
            }
            set
            {
                this.applicationCommonBenefitsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("RecommendedList", IsNullable = false)]
        public List<DataForDeleteRecommendedList> RecommendedLists
        {
            get
            {
                return this.recommendedListsField;
            }
            set
            {
                this.recommendedListsField = value;
            }
        }
    }

    public partial class DataForDeleteApplication
    {

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    public partial class DataForDeleteOrdersOfAdmission
    {

        private DataForDeleteOrdersOfAdmissionApplication applicationField;

        private List<string> ordersOfAdmissionField;

        
        public DataForDeleteOrdersOfAdmission()
        {
            //this.ordersOfAdmissionField = new List<string>();
            //this.applicationField = new List<DataForDeleteOrdersOfAdmissionApplication>();
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Application", IsNullable = false)]
        public DataForDeleteOrdersOfAdmissionApplication Application
        {
            get
            {
                return this.applicationField;
            }
            set
            {
                this.applicationField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("OrderOfAdmissionUID", IsNullable = false)]
        public List<string> OrdersOfAdmission
        {
            get
            {
                return this.ordersOfAdmissionField;
            }
            set
            {
                this.ordersOfAdmissionField = value;
            }
        }
    }

   
    public partial class DataForDeleteOrdersOfAdmissionApplication
    {

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        private bool registrationDateFieldSpecified;

        private string uIDField;

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegistrationDateSpecified
        {
            get { return true; }
            set
            {
                this.registrationDateFieldSpecified = value;
            }
        }

        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class DataForDeleteOrdersOfAdmissionOrdersOfAdmission
    {

        private string orderOfAdmissionUIDField;

        public string OrderOfAdmissionUID
        {
            get
            {
                return this.orderOfAdmissionUIDField;
            }
            set
            {
                this.orderOfAdmissionUIDField = value;
            }
        }
    }

    public partial class DataForDeleteCompetitiveGroups
    {

        private List<object> itemsField;

        public DataForDeleteCompetitiveGroups()
        {
            this.itemsField = new List<object>();
        }

        public List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    public partial class DataForDeleteCampaigns
    {

        private List<object> itemsField;

        public DataForDeleteCampaigns()
        {
            this.itemsField = new List<object>();
        }

        public List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    public partial class DataForDeleteCompetitiveGroupItems
    {

        private List<object> itemsField;

        public DataForDeleteCompetitiveGroupItems()
        {
            this.itemsField = new List<object>();
        }

        public List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    public partial class DataForDeleteEntranceTestResults
    {

        private List<object> itemsField;

        public DataForDeleteEntranceTestResults()
        {
            this.itemsField = new List<object>();
        }

        public List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    public partial class DataForDeleteApplicationCommonBenefits
    {

        private List<object> itemsField;

        public DataForDeleteApplicationCommonBenefits()
        {
            this.itemsField = new List<object>();
        }

        public List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    public partial class DataForDeleteRecommendedList
    {

        private int stageField;

        private List<DataForDeleteRecommendedListRecList> recListsField;

        public DataForDeleteRecommendedList()
        {
            this.recListsField = new List<DataForDeleteRecommendedListRecList>();
        }

        public int Stage
        {
            get
            {
                return this.stageField;
            }
            set
            {
                this.stageField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("RecList", IsNullable = false)]
        public List<DataForDeleteRecommendedListRecList> RecLists
        {
            get
            {
                return this.recListsField;
            }
            set
            {
                this.recListsField = value;
            }
        }
    }

    public partial class DataForDeleteRecommendedListRecList
    {

        private object applicationNumberField;

        private System.DateTime registrationDateField;

        public object ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    public partial class Root
    {

        private DataForDelete dataForDeleteField;


        public DataForDelete DataForDelete
        {
            get
            {
                return this.dataForDeleteField;
            }
            set
            {
                this.dataForDeleteField = value;
            }
        }
    }
}
