//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18033
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fdalilibtests {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestRes() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fdalilibtests.TestRes", typeof(TestRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;BasicDiplomaDocument&gt;
        ///                &lt;OriginalReceived&gt;0&lt;/OriginalReceived&gt;
        ///                &lt;DocumentNumber&gt;0043716&lt;/DocumentNumber&gt;
        ///                &lt;DocumentDate&gt;22.06.2013 0:00:00&lt;/DocumentDate&gt;
        ///                &lt;DocumentOrganization&gt;УИТ г. Ухта&lt;/DocumentOrganization&gt;
        ///                &lt;DocumentSeries&gt;90НПА&lt;/DocumentSeries&gt;
        ///                &lt;RegistrationNumber&gt;90НПА 0043716&lt;/RegistrationNumber&gt;
        ///                &lt;QualificationTypeID&gt;0&lt;/QualificationTypeID&gt;
        ///              &lt;/BasicDiplomaDocument&gt;.
        /// </summary>
        internal static string BasicDiploma {
            get {
                return ResourceManager.GetString("BasicDiploma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;CampaignDate&gt;
        ///            &lt;Course&gt;1&lt;/Course&gt;
        ///            &lt;EducationLevelID&gt;2&lt;/EducationLevelID&gt;
        ///            &lt;EducationFormID&gt;10&lt;/EducationFormID&gt;
        ///            &lt;EducationSourceID&gt;14&lt;/EducationSourceID&gt;
        ///            &lt;DateStart&gt;2013-06-20&lt;/DateStart&gt;
        ///            &lt;DateEnd&gt;2013-07-25&lt;/DateEnd&gt;
        ///            &lt;DateOrder&gt;2013-08-10&lt;/DateOrder&gt;
        ///          &lt;/CampaignDate&gt;.
        /// </summary>
        internal static string CampainDate {
            get {
                return ResourceManager.GetString("CampainDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;AppSingleCheckResult xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;EgeDocumentCheckResults&gt;
        ///    &lt;Application&gt;
        ///      &lt;ApplicationNumber&gt;5718&lt;/ApplicationNumber&gt;
        ///      &lt;OrderOfAdmissionId xsi:nil=&quot;true&quot; /&gt;
        ///      &lt;RegistrationDate&gt;2013-06-26T00:00:00.0000000+04:00&lt;/RegistrationDate&gt;
        ///    &lt;/Application&gt;
        ///    &lt;EgeDocuments /&gt;
        ///  &lt;/EgeDocumentCheckResults&gt;
        ///  &lt;GetEgeDocuments&gt;
        ///    &lt;Application&gt;
        ///      &lt;ApplicationNumber&gt;5718&lt;/ApplicationNumber&gt;
        ///     [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string CheckSingleAppRes {
            get {
                return ResourceManager.GetString("CheckSingleAppRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;EgeDocumentCheckResult xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///    &lt;Application&gt;
        ///      &lt;ApplicationNumber&gt;5718&lt;/ApplicationNumber&gt;
        ///      &lt;OrderOfAdmissionId xsi:nil=&quot;true&quot; /&gt;
        ///      &lt;RegistrationDate&gt;2013-06-26T00:00:00.0000000+04:00&lt;/RegistrationDate&gt;
        ///    &lt;/Application&gt;
        ///    &lt;EgeDocuments /&gt;
        ///&lt;/EgeDocumentCheckResult&gt;.
        /// </summary>
        internal static string EgeDocumentCheckResultRes {
            get {
                return ResourceManager.GetString("EgeDocumentCheckResultRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;InstitutionExports xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;InstitutionExport&gt;
        ///    &lt;InstitutionDetails&gt;
        ///      &lt;InstitutionID&gt;6377&lt;/InstitutionID&gt;
        ///      &lt;IsFilial&gt;false&lt;/IsFilial&gt;
        ///      &lt;FullName&gt;Федеральное государственное бюджетное образовательное учреждение высшего профессионального образования &quot;Ухтинский государственный технический университет&quot;&lt;/FullName&gt;
        ///      &lt;BriefName&gt;ФГБОУ ВПО УГТУ&lt;/BriefName&gt;
        ///      &lt;FormOfLawID&gt;3&lt;/FormOfLawID&gt;
        ///  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string InstitutionInfoRes {
            get {
                return ResourceManager.GetString("InstitutionInfoRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;RegistrationDate&gt;2013-06-26T00:00:00.0000000&lt;/RegistrationDate&gt;.
        /// </summary>
        internal static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
    }
}
