//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18033
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using Fdalilib.ImportClasses;

// 
// Этот исходный код был создан с помощью xsd, версия=4.0.30319.17929.
// 


namespace Fdalilib.ImportClasses.Ege
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetEgeDocument {
    
        private ShortApplication applicationField;
    
        private EgeDocument[] egeDocumentsField;
    
        private string errorField;
    
        /// <remarks/>
        public ShortApplication Application
        {
            get {
                return this.applicationField;
            }
            set {
                this.applicationField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("EgeDocument", IsNullable=false)]
        public EgeDocument[] EgeDocuments {
            get {
                return this.egeDocumentsField;
            }
            set {
                this.egeDocumentsField = value;
            }
        }
    
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
}