// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>Fdalilib</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Fdalilib.Actions2016.GetDeleteResult
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class DeleteResultPackage
    {

        private DeleteResultPackageLog logField;

        private DeleteResultPackageConflicts conflictsField;

        public DeleteResultPackage()
        {
            this.conflictsField = new DeleteResultPackageConflicts();
            this.logField = new DeleteResultPackageLog();
        }

        public DeleteResultPackageLog Log
        {
            get
            {
                return this.logField;
            }
            set
            {
                this.logField = value;
            }
        }

        public DeleteResultPackageConflicts Conflicts
        {
            get
            {
                return this.conflictsField;
            }
            set
            {
                this.conflictsField = value;
            }
        }
    }

    public partial class DeleteResultPackageLog
    {

        private DeleteResultPackageLogFailed failedField;

        private DeleteResultPackageLogSuccessful successfulField;

        public DeleteResultPackageLog()
        {
            this.successfulField = new DeleteResultPackageLogSuccessful();
            this.failedField = new DeleteResultPackageLogFailed();
        }

        public DeleteResultPackageLogFailed Failed
        {
            get
            {
                return this.failedField;
            }
            set
            {
                this.failedField = value;
            }
        }

        public DeleteResultPackageLogSuccessful Successful
        {
            get
            {
                return this.successfulField;
            }
            set
            {
                this.successfulField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailed
    {

        private List<DeleteResultPackageLogFailedAdmissionVolume> admissionVolumesField;

        private DeleteResultPackageLogFailedDistributedAdmissionVolumes distributedAdmissionVolumesField;

        private List<DeleteResultPackageLogFailedInstitutionAchievement> institutionAchievementsField;

        private List<DeleteResultPackageLogFailedCompetitiveGroup> competitiveGroupsField;

        private List<DeleteResultPackageLogFailedCompetitiveGroupItem> competitiveGroupItemsField;

        private List<DeleteResultPackageLogFailedTargetOrganization> targetOrganizationsField;

        private List<DeleteResultPackageLogFailedTargetOrganizationDirection> targetOrganizationDirectionsField;

        private List<DeleteResultPackageLogFailedEntranceTestItem> entranceTestItemsField;

        private List<DeleteResultPackageLogFailedCommonBenefitItem> commonBenefitField;

        private List<DeleteResultPackageLogFailedEntranceTestBenefitItem> entranceTestBenefitsField;

        private List<DeleteResultPackageLogFailedApplication> applicationsField;

        private List<DeleteResultPackageLogFailedOlympicDocument> olympicDocumentsField;

        private List<DeleteResultPackageLogFailedOlympicTotalDocument> olympicTotalDocumentsField;

        private List<DeleteResultPackageLogFailedDisabilityDocument> disabilityDocumentsField;

        private List<DeleteResultPackageLogFailedMedicalDocument> medicalDocumentsField;

        private List<DeleteResultPackageLogFailedAllowEducationDocument> allowEducationDocumentsField;

        private List<DeleteResultPackageLogFailedCampaign> campaignsField;

        private List<DeleteResultPackageLogFailedCustomDocument> customDocumentsField;

        private List<DeleteResultPackageLogFailedEntranceTestResult> entranceTestResultsField;

        private List<DeleteResultPackageLogFailedApplicationCommonBenefit> applicationCommonBenefitsField;

        private DeleteResultPackageLogFailedApplicationsInOrders applicationsInOrdersField;

        private DeleteResultPackageLogFailedOrderOfAdmission orderOfAdmissionField;

        public DeleteResultPackageLogFailed()
        {
            this.orderOfAdmissionField = new DeleteResultPackageLogFailedOrderOfAdmission();
            this.applicationsInOrdersField = new DeleteResultPackageLogFailedApplicationsInOrders();
            this.applicationCommonBenefitsField = new List<DeleteResultPackageLogFailedApplicationCommonBenefit>();
            this.entranceTestResultsField = new List<DeleteResultPackageLogFailedEntranceTestResult>();
            this.customDocumentsField = new List<DeleteResultPackageLogFailedCustomDocument>();
            this.campaignsField = new List<DeleteResultPackageLogFailedCampaign>();
            this.allowEducationDocumentsField = new List<DeleteResultPackageLogFailedAllowEducationDocument>();
            this.medicalDocumentsField = new List<DeleteResultPackageLogFailedMedicalDocument>();
            this.disabilityDocumentsField = new List<DeleteResultPackageLogFailedDisabilityDocument>();
            this.olympicTotalDocumentsField = new List<DeleteResultPackageLogFailedOlympicTotalDocument>();
            this.olympicDocumentsField = new List<DeleteResultPackageLogFailedOlympicDocument>();
            this.applicationsField = new List<DeleteResultPackageLogFailedApplication>();
            this.entranceTestBenefitsField = new List<DeleteResultPackageLogFailedEntranceTestBenefitItem>();
            this.commonBenefitField = new List<DeleteResultPackageLogFailedCommonBenefitItem>();
            this.entranceTestItemsField = new List<DeleteResultPackageLogFailedEntranceTestItem>();
            this.targetOrganizationDirectionsField = new List<DeleteResultPackageLogFailedTargetOrganizationDirection>();
            this.targetOrganizationsField = new List<DeleteResultPackageLogFailedTargetOrganization>();
            this.competitiveGroupItemsField = new List<DeleteResultPackageLogFailedCompetitiveGroupItem>();
            this.competitiveGroupsField = new List<DeleteResultPackageLogFailedCompetitiveGroup>();
            this.institutionAchievementsField = new List<DeleteResultPackageLogFailedInstitutionAchievement>();
            this.distributedAdmissionVolumesField = new DeleteResultPackageLogFailedDistributedAdmissionVolumes();
            this.admissionVolumesField = new List<DeleteResultPackageLogFailedAdmissionVolume>();
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("AdmissionVolume", IsNullable = false)]
        public List<DeleteResultPackageLogFailedAdmissionVolume> AdmissionVolumes
        {
            get
            {
                return this.admissionVolumesField;
            }
            set
            {
                this.admissionVolumesField = value;
            }
        }

        public DeleteResultPackageLogFailedDistributedAdmissionVolumes DistributedAdmissionVolumes
        {
            get
            {
                return this.distributedAdmissionVolumesField;
            }
            set
            {
                this.distributedAdmissionVolumesField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("InstitutionAchievement", IsNullable = false)]
        public List<DeleteResultPackageLogFailedInstitutionAchievement> InstitutionAchievements
        {
            get
            {
                return this.institutionAchievementsField;
            }
            set
            {
                this.institutionAchievementsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("CompetitiveGroup", IsNullable = false)]
        public List<DeleteResultPackageLogFailedCompetitiveGroup> CompetitiveGroups
        {
            get
            {
                return this.competitiveGroupsField;
            }
            set
            {
                this.competitiveGroupsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("CompetitiveGroupItem", IsNullable = false)]
        public List<DeleteResultPackageLogFailedCompetitiveGroupItem> CompetitiveGroupItems
        {
            get
            {
                return this.competitiveGroupItemsField;
            }
            set
            {
                this.competitiveGroupItemsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("TargetOrganization", IsNullable = false)]
        public List<DeleteResultPackageLogFailedTargetOrganization> TargetOrganizations
        {
            get
            {
                return this.targetOrganizationsField;
            }
            set
            {
                this.targetOrganizationsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("TargetOrganizationDirection", IsNullable = false)]
        public List<DeleteResultPackageLogFailedTargetOrganizationDirection> TargetOrganizationDirections
        {
            get
            {
                return this.targetOrganizationDirectionsField;
            }
            set
            {
                this.targetOrganizationDirectionsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("EntranceTestItem", IsNullable = false)]
        public List<DeleteResultPackageLogFailedEntranceTestItem> EntranceTestItems
        {
            get
            {
                return this.entranceTestItemsField;
            }
            set
            {
                this.entranceTestItemsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("CommonBenefitItem", IsNullable = false)]
        public List<DeleteResultPackageLogFailedCommonBenefitItem> CommonBenefit
        {
            get
            {
                return this.commonBenefitField;
            }
            set
            {
                this.commonBenefitField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("EntranceTestBenefitItem", IsNullable = false)]
        public List<DeleteResultPackageLogFailedEntranceTestBenefitItem> EntranceTestBenefits
        {
            get
            {
                return this.entranceTestBenefitsField;
            }
            set
            {
                this.entranceTestBenefitsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Application", IsNullable = false)]
        public List<DeleteResultPackageLogFailedApplication> Applications
        {
            get
            {
                return this.applicationsField;
            }
            set
            {
                this.applicationsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("OlympicDocument", IsNullable = false)]
        public List<DeleteResultPackageLogFailedOlympicDocument> OlympicDocuments
        {
            get
            {
                return this.olympicDocumentsField;
            }
            set
            {
                this.olympicDocumentsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("OlympicTotalDocument", IsNullable = false)]
        public List<DeleteResultPackageLogFailedOlympicTotalDocument> OlympicTotalDocuments
        {
            get
            {
                return this.olympicTotalDocumentsField;
            }
            set
            {
                this.olympicTotalDocumentsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("DisabilityDocument", IsNullable = false)]
        public List<DeleteResultPackageLogFailedDisabilityDocument> DisabilityDocuments
        {
            get
            {
                return this.disabilityDocumentsField;
            }
            set
            {
                this.disabilityDocumentsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("MedicalDocument", IsNullable = false)]
        public List<DeleteResultPackageLogFailedMedicalDocument> MedicalDocuments
        {
            get
            {
                return this.medicalDocumentsField;
            }
            set
            {
                this.medicalDocumentsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("AllowEducationDocument", IsNullable = false)]
        public List<DeleteResultPackageLogFailedAllowEducationDocument> AllowEducationDocuments
        {
            get
            {
                return this.allowEducationDocumentsField;
            }
            set
            {
                this.allowEducationDocumentsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Campaign", IsNullable = false)]
        public List<DeleteResultPackageLogFailedCampaign> Campaigns
        {
            get
            {
                return this.campaignsField;
            }
            set
            {
                this.campaignsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("CustomDocument", IsNullable = false)]
        public List<DeleteResultPackageLogFailedCustomDocument> CustomDocuments
        {
            get
            {
                return this.customDocumentsField;
            }
            set
            {
                this.customDocumentsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("EntranceTestResult", IsNullable = false)]
        public List<DeleteResultPackageLogFailedEntranceTestResult> EntranceTestResults
        {
            get
            {
                return this.entranceTestResultsField;
            }
            set
            {
                this.entranceTestResultsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("ApplicationCommonBenefit", IsNullable = false)]
        public List<DeleteResultPackageLogFailedApplicationCommonBenefit> ApplicationCommonBenefits
        {
            get
            {
                return this.applicationCommonBenefitsField;
            }
            set
            {
                this.applicationCommonBenefitsField = value;
            }
        }

        public DeleteResultPackageLogFailedApplicationsInOrders ApplicationsInOrders
        {
            get
            {
                return this.applicationsInOrdersField;
            }
            set
            {
                this.applicationsInOrdersField = value;
            }
        }

        public DeleteResultPackageLogFailedOrderOfAdmission OrderOfAdmission
        {
            get
            {
                return this.orderOfAdmissionField;
            }
            set
            {
                this.orderOfAdmissionField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailedAdmissionVolume
    {

        private TErrorInfo errorInfoField;

        private object educationLevelNameField;

        private object directionNameField;

        public DeleteResultPackageLogFailedAdmissionVolume()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public object EducationLevelName
        {
            get
            {
                return this.educationLevelNameField;
            }
            set
            {
                this.educationLevelNameField = value;
            }
        }

        public object DirectionName
        {
            get
            {
                return this.directionNameField;
            }
            set
            {
                this.directionNameField = value;
            }
        }
    }

    public partial class TErrorInfo
    {

        private uint errorCodeField;

        private string messageField;

        private TErrorInfoConflictItemsInfo conflictItemsInfoField;

        public TErrorInfo()
        {
            this.conflictItemsInfoField = new TErrorInfoConflictItemsInfo();
        }

        public uint ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }

        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        public TErrorInfoConflictItemsInfo ConflictItemsInfo
        {
            get
            {
                return this.conflictItemsInfoField;
            }
            set
            {
                this.conflictItemsInfoField = value;
            }
        }
    }

    public partial class TErrorInfoConflictItemsInfo
    {

        private List<TErrorInfoConflictItemsInfoApplication> applicationsField;

        private List<TErrorInfoConflictItemsInfoApplication1> ordersOfAdmissionField;

        private TErrorInfoConflictItemsInfoCompetitiveGroupItems competitiveGroupItemsField;

        private TErrorInfoConflictItemsInfoEntranceTestResults entranceTestResultsField;

        private TErrorInfoConflictItemsInfoApplicationCommonBenefits applicationCommonBenefitsField;

        private TErrorInfoConflictItemsInfoInstitutionAchievements institutionAchievementsField;

        public TErrorInfoConflictItemsInfo()
        {
            this.institutionAchievementsField = new TErrorInfoConflictItemsInfoInstitutionAchievements();
            this.applicationCommonBenefitsField = new TErrorInfoConflictItemsInfoApplicationCommonBenefits();
            this.entranceTestResultsField = new TErrorInfoConflictItemsInfoEntranceTestResults();
            this.competitiveGroupItemsField = new TErrorInfoConflictItemsInfoCompetitiveGroupItems();
            this.ordersOfAdmissionField = new List<TErrorInfoConflictItemsInfoApplication1>();
            this.applicationsField = new List<TErrorInfoConflictItemsInfoApplication>();
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Application", IsNullable = false)]
        public List<TErrorInfoConflictItemsInfoApplication> Applications
        {
            get
            {
                return this.applicationsField;
            }
            set
            {
                this.applicationsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Application", IsNullable = false)]
        public List<TErrorInfoConflictItemsInfoApplication1> OrdersOfAdmission
        {
            get
            {
                return this.ordersOfAdmissionField;
            }
            set
            {
                this.ordersOfAdmissionField = value;
            }
        }

        public TErrorInfoConflictItemsInfoCompetitiveGroupItems CompetitiveGroupItems
        {
            get
            {
                return this.competitiveGroupItemsField;
            }
            set
            {
                this.competitiveGroupItemsField = value;
            }
        }

        public TErrorInfoConflictItemsInfoEntranceTestResults EntranceTestResults
        {
            get
            {
                return this.entranceTestResultsField;
            }
            set
            {
                this.entranceTestResultsField = value;
            }
        }

        public TErrorInfoConflictItemsInfoApplicationCommonBenefits ApplicationCommonBenefits
        {
            get
            {
                return this.applicationCommonBenefitsField;
            }
            set
            {
                this.applicationCommonBenefitsField = value;
            }
        }

        public TErrorInfoConflictItemsInfoInstitutionAchievements InstitutionAchievements
        {
            get
            {
                return this.institutionAchievementsField;
            }
            set
            {
                this.institutionAchievementsField = value;
            }
        }
    }

    public partial class TErrorInfoConflictItemsInfoApplication
    {

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        private string uIDField;

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }

        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class TError
    {

        private string errorCodeField;

        private string errorTextField;

        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }

        public string ErrorText
        {
            get
            {
                return this.errorTextField;
            }
            set
            {
                this.errorTextField = value;
            }
        }
    }

    public partial class TErrorInfoConflictItemsInfoApplication1
    {

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        private string uIDField;

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }

        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class TErrorInfoConflictItemsInfoCompetitiveGroupItems
    {

        private List<uint> competitiveGroupItemIDField;

        private List<string> uIDField;

        public TErrorInfoConflictItemsInfoCompetitiveGroupItems()
        {
            this.uIDField = new List<string>();
            this.competitiveGroupItemIDField = new List<uint>();
        }

        public List<uint> CompetitiveGroupItemID
        {
            get
            {
                return this.competitiveGroupItemIDField;
            }
            set
            {
                this.competitiveGroupItemIDField = value;
            }
        }

        public List<string> UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class TErrorInfoConflictItemsInfoEntranceTestResults
    {

        private List<uint> entranceTestsResultIDField;

        private List<string> uIDField;

        public TErrorInfoConflictItemsInfoEntranceTestResults()
        {
            this.uIDField = new List<string>();
            this.entranceTestsResultIDField = new List<uint>();
        }

        public List<uint> EntranceTestsResultID
        {
            get
            {
                return this.entranceTestsResultIDField;
            }
            set
            {
                this.entranceTestsResultIDField = value;
            }
        }

        public List<string> UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class TErrorInfoConflictItemsInfoApplicationCommonBenefits
    {

        private List<uint> applicationCommonBenefitIDField;

        private List<string> uIDField;

        public TErrorInfoConflictItemsInfoApplicationCommonBenefits()
        {
            this.uIDField = new List<string>();
            this.applicationCommonBenefitIDField = new List<uint>();
        }

        public List<uint> ApplicationCommonBenefitID
        {
            get
            {
                return this.applicationCommonBenefitIDField;
            }
            set
            {
                this.applicationCommonBenefitIDField = value;
            }
        }

        public List<string> UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class TErrorInfoConflictItemsInfoInstitutionAchievements
    {

        private List<uint> institutionAchievementIDField;

        private List<string> uIDField;

        public TErrorInfoConflictItemsInfoInstitutionAchievements()
        {
            this.uIDField = new List<string>();
            this.institutionAchievementIDField = new List<uint>();
        }

        public List<uint> InstitutionAchievementID
        {
            get
            {
                return this.institutionAchievementIDField;
            }
            set
            {
                this.institutionAchievementIDField = value;
            }
        }

        public List<string> UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailedDistributedAdmissionVolumes
    {

        private DeleteResultPackageLogFailedDistributedAdmissionVolumesDistributedAdmissionVolume distributedAdmissionVolumeField;

        public DeleteResultPackageLogFailedDistributedAdmissionVolumes()
        {
            this.distributedAdmissionVolumeField = new DeleteResultPackageLogFailedDistributedAdmissionVolumesDistributedAdmissionVolume();
        }

        public DeleteResultPackageLogFailedDistributedAdmissionVolumesDistributedAdmissionVolume DistributedAdmissionVolume
        {
            get
            {
                return this.distributedAdmissionVolumeField;
            }
            set
            {
                this.distributedAdmissionVolumeField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailedDistributedAdmissionVolumesDistributedAdmissionVolume
    {

        private TErrorInfo errorInfoField;

        private string admissionVolumeUIDField;

        private uint levelBudgetField;

        public DeleteResultPackageLogFailedDistributedAdmissionVolumesDistributedAdmissionVolume()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string AdmissionVolumeUID
        {
            get
            {
                return this.admissionVolumeUIDField;
            }
            set
            {
                this.admissionVolumeUIDField = value;
            }
        }

        public uint LevelBudget
        {
            get
            {
                return this.levelBudgetField;
            }
            set
            {
                this.levelBudgetField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailedInstitutionAchievement
    {

        private TErrorInfo errorInfoField;

        private string iAUIDField;

        private string nameField;

        public DeleteResultPackageLogFailedInstitutionAchievement()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string IAUID
        {
            get
            {
                return this.iAUIDField;
            }
            set
            {
                this.iAUIDField = value;
            }
        }

        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailedCompetitiveGroup
    {

        private TErrorInfo errorInfoField;

        private string competitiveGroupNameField;

        public DeleteResultPackageLogFailedCompetitiveGroup()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string CompetitiveGroupName
        {
            get
            {
                return this.competitiveGroupNameField;
            }
            set
            {
                this.competitiveGroupNameField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailedCompetitiveGroupItem
    {

        private TErrorInfo errorInfoField;

        private string directionCodeField;

        private string directionNameField;

        private string competitiveGroupNameField;

        public DeleteResultPackageLogFailedCompetitiveGroupItem()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string DirectionCode
        {
            get
            {
                return this.directionCodeField;
            }
            set
            {
                this.directionCodeField = value;
            }
        }

        public string DirectionName
        {
            get
            {
                return this.directionNameField;
            }
            set
            {
                this.directionNameField = value;
            }
        }

        public string CompetitiveGroupName
        {
            get
            {
                return this.competitiveGroupNameField;
            }
            set
            {
                this.competitiveGroupNameField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailedTargetOrganization
    {

        private TErrorInfo errorInfoField;

        private string targetOrganizationNameField;

        private string competitiveGroupNameField;

        public DeleteResultPackageLogFailedTargetOrganization()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string TargetOrganizationName
        {
            get
            {
                return this.targetOrganizationNameField;
            }
            set
            {
                this.targetOrganizationNameField = value;
            }
        }

        public string CompetitiveGroupName
        {
            get
            {
                return this.competitiveGroupNameField;
            }
            set
            {
                this.competitiveGroupNameField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailedTargetOrganizationDirection
    {

        private TErrorInfo errorInfoField;

        private string directionNameField;

        private string educationLevelNameField;

        private string targetOrganizationNameField;

        private string competitiveGroupNameField;

        public DeleteResultPackageLogFailedTargetOrganizationDirection()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string DirectionName
        {
            get
            {
                return this.directionNameField;
            }
            set
            {
                this.directionNameField = value;
            }
        }

        public string EducationLevelName
        {
            get
            {
                return this.educationLevelNameField;
            }
            set
            {
                this.educationLevelNameField = value;
            }
        }

        public string TargetOrganizationName
        {
            get
            {
                return this.targetOrganizationNameField;
            }
            set
            {
                this.targetOrganizationNameField = value;
            }
        }

        public string CompetitiveGroupName
        {
            get
            {
                return this.competitiveGroupNameField;
            }
            set
            {
                this.competitiveGroupNameField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailedEntranceTestItem
    {

        private TErrorInfo errorInfoField;

        private string entranceTestTypeField;

        private string subjectNameField;

        private string competitiveGroupNameField;

        public DeleteResultPackageLogFailedEntranceTestItem()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string EntranceTestType
        {
            get
            {
                return this.entranceTestTypeField;
            }
            set
            {
                this.entranceTestTypeField = value;
            }
        }

        public string SubjectName
        {
            get
            {
                return this.subjectNameField;
            }
            set
            {
                this.subjectNameField = value;
            }
        }

        public string CompetitiveGroupName
        {
            get
            {
                return this.competitiveGroupNameField;
            }
            set
            {
                this.competitiveGroupNameField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailedCommonBenefitItem
    {

        private TErrorInfo errorInfoField;

        private string benefitKindNameField;

        private string competitiveGroupNameField;

        public DeleteResultPackageLogFailedCommonBenefitItem()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string BenefitKindName
        {
            get
            {
                return this.benefitKindNameField;
            }
            set
            {
                this.benefitKindNameField = value;
            }
        }

        public string CompetitiveGroupName
        {
            get
            {
                return this.competitiveGroupNameField;
            }
            set
            {
                this.competitiveGroupNameField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailedEntranceTestBenefitItem
    {

        private TErrorInfo errorInfoField;

        private string benefitKindNameField;

        private string entranceTestTypeField;

        private string subjectNameField;

        private string competitiveGroupNameField;

        public DeleteResultPackageLogFailedEntranceTestBenefitItem()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string BenefitKindName
        {
            get
            {
                return this.benefitKindNameField;
            }
            set
            {
                this.benefitKindNameField = value;
            }
        }

        public string EntranceTestType
        {
            get
            {
                return this.entranceTestTypeField;
            }
            set
            {
                this.entranceTestTypeField = value;
            }
        }

        public string SubjectName
        {
            get
            {
                return this.subjectNameField;
            }
            set
            {
                this.subjectNameField = value;
            }
        }

        public string CompetitiveGroupName
        {
            get
            {
                return this.competitiveGroupNameField;
            }
            set
            {
                this.competitiveGroupNameField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailedApplication
    {

        private TErrorInfo errorInfoField;

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        public DeleteResultPackageLogFailedApplication()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailedOlympicDocument
    {

        private TErrorInfo errorInfoField;

        private string documentNumberField;

        private System.DateTime documentDateField;

        private bool documentDateFieldSpecified;

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        public DeleteResultPackageLogFailedOlympicDocument()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string DocumentNumber
        {
            get
            {
                return this.documentNumberField;
            }
            set
            {
                this.documentNumberField = value;
            }
        }

        public System.DateTime DocumentDate
        {
            get
            {
                return this.documentDateField;
            }
            set
            {
                this.documentDateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentDateSpecified
        {
            get
            {
                return this.documentDateFieldSpecified;
            }
            set
            {
                this.documentDateFieldSpecified = value;
            }
        }

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailedOlympicTotalDocument
    {

        private TErrorInfo errorInfoField;

        private string documentNumberField;

        private System.DateTime documentDateField;

        private bool documentDateFieldSpecified;

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        public DeleteResultPackageLogFailedOlympicTotalDocument()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string DocumentNumber
        {
            get
            {
                return this.documentNumberField;
            }
            set
            {
                this.documentNumberField = value;
            }
        }

        public System.DateTime DocumentDate
        {
            get
            {
                return this.documentDateField;
            }
            set
            {
                this.documentDateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentDateSpecified
        {
            get
            {
                return this.documentDateFieldSpecified;
            }
            set
            {
                this.documentDateFieldSpecified = value;
            }
        }

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailedDisabilityDocument
    {

        private TErrorInfo errorInfoField;

        private string documentNumberField;

        private System.DateTime documentDateField;

        private bool documentDateFieldSpecified;

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        public DeleteResultPackageLogFailedDisabilityDocument()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string DocumentNumber
        {
            get
            {
                return this.documentNumberField;
            }
            set
            {
                this.documentNumberField = value;
            }
        }

        public System.DateTime DocumentDate
        {
            get
            {
                return this.documentDateField;
            }
            set
            {
                this.documentDateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentDateSpecified
        {
            get
            {
                return this.documentDateFieldSpecified;
            }
            set
            {
                this.documentDateFieldSpecified = value;
            }
        }

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailedMedicalDocument
    {

        private TErrorInfo errorInfoField;

        private string documentNumberField;

        private System.DateTime documentDateField;

        private bool documentDateFieldSpecified;

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        public DeleteResultPackageLogFailedMedicalDocument()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string DocumentNumber
        {
            get
            {
                return this.documentNumberField;
            }
            set
            {
                this.documentNumberField = value;
            }
        }

        public System.DateTime DocumentDate
        {
            get
            {
                return this.documentDateField;
            }
            set
            {
                this.documentDateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentDateSpecified
        {
            get
            {
                return this.documentDateFieldSpecified;
            }
            set
            {
                this.documentDateFieldSpecified = value;
            }
        }

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailedAllowEducationDocument
    {

        private TErrorInfo errorInfoField;

        private string documentNumberField;

        private System.DateTime documentDateField;

        private bool documentDateFieldSpecified;

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        public DeleteResultPackageLogFailedAllowEducationDocument()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string DocumentNumber
        {
            get
            {
                return this.documentNumberField;
            }
            set
            {
                this.documentNumberField = value;
            }
        }

        public System.DateTime DocumentDate
        {
            get
            {
                return this.documentDateField;
            }
            set
            {
                this.documentDateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentDateSpecified
        {
            get
            {
                return this.documentDateFieldSpecified;
            }
            set
            {
                this.documentDateFieldSpecified = value;
            }
        }

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailedCampaign
    {

        private TErrorInfo errorInfoField;

        private string nameField;

        public DeleteResultPackageLogFailedCampaign()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailedCustomDocument
    {

        private TErrorInfo errorInfoField;

        private string documentNumberField;

        private System.DateTime documentDateField;

        private bool documentDateFieldSpecified;

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        public DeleteResultPackageLogFailedCustomDocument()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string DocumentNumber
        {
            get
            {
                return this.documentNumberField;
            }
            set
            {
                this.documentNumberField = value;
            }
        }

        public System.DateTime DocumentDate
        {
            get
            {
                return this.documentDateField;
            }
            set
            {
                this.documentDateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentDateSpecified
        {
            get
            {
                return this.documentDateFieldSpecified;
            }
            set
            {
                this.documentDateFieldSpecified = value;
            }
        }

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailedEntranceTestResult
    {

        private TErrorInfo errorInfoField;

        private string resultSourceTypeField;

        private string subjectNameField;

        private decimal resultValueField;

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        public DeleteResultPackageLogFailedEntranceTestResult()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string ResultSourceType
        {
            get
            {
                return this.resultSourceTypeField;
            }
            set
            {
                this.resultSourceTypeField = value;
            }
        }

        public string SubjectName
        {
            get
            {
                return this.subjectNameField;
            }
            set
            {
                this.subjectNameField = value;
            }
        }

        public decimal ResultValue
        {
            get
            {
                return this.resultValueField;
            }
            set
            {
                this.resultValueField = value;
            }
        }

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailedApplicationCommonBenefit
    {

        private TErrorInfo errorInfoField;

        private string benefitKindNameField;

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        public DeleteResultPackageLogFailedApplicationCommonBenefit()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string BenefitKindName
        {
            get
            {
                return this.benefitKindNameField;
            }
            set
            {
                this.benefitKindNameField = value;
            }
        }

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailedApplicationsInOrders
    {

        private TErrorInfo errorInfoField;

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        private string uIDField;

        public DeleteResultPackageLogFailedApplicationsInOrders()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }

        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogFailedOrderOfAdmission
    {

        private TErrorInfo errorInfoField;

        private string orderUIDField;

        private string orderNameField;

        private uint orderNumberField;

        private System.DateTime orderDateField;

        public DeleteResultPackageLogFailedOrderOfAdmission()
        {
            this.errorInfoField = new TErrorInfo();
        }

        public TErrorInfo ErrorInfo
        {
            get
            {
                return this.errorInfoField;
            }
            set
            {
                this.errorInfoField = value;
            }
        }

        public string OrderUID
        {
            get
            {
                return this.orderUIDField;
            }
            set
            {
                this.orderUIDField = value;
            }
        }

        public string OrderName
        {
            get
            {
                return this.orderNameField;
            }
            set
            {
                this.orderNameField = value;
            }
        }

        public uint OrderNumber
        {
            get
            {
                return this.orderNumberField;
            }
            set
            {
                this.orderNumberField = value;
            }
        }

        public System.DateTime OrderDate
        {
            get
            {
                return this.orderDateField;
            }
            set
            {
                this.orderDateField = value;
            }
        }
    }

    public partial class DeleteResultPackageLogSuccessful
    {

        private uint campaignsField;

        private uint admissionVolumesField;

        private byte competitiveGroupsField;

        private uint competitiveGroupItemsField;

        private uint distributedAdmissionVolumesField;

        private uint institutionAchievementsField;

        private uint targetOrganizationsField;

        private uint applicationsField;

        private uint ordersField;

        private uint applicationsInOrdersField;

        public uint Campaigns
        {
            get
            {
                return this.campaignsField;
            }
            set
            {
                this.campaignsField = value;
            }
        }

        public uint AdmissionVolumes
        {
            get
            {
                return this.admissionVolumesField;
            }
            set
            {
                this.admissionVolumesField = value;
            }
        }

        public byte CompetitiveGroups
        {
            get
            {
                return this.competitiveGroupsField;
            }
            set
            {
                this.competitiveGroupsField = value;
            }
        }

        public uint CompetitiveGroupItems
        {
            get
            {
                return this.competitiveGroupItemsField;
            }
            set
            {
                this.competitiveGroupItemsField = value;
            }
        }

        public uint DistributedAdmissionVolumes
        {
            get
            {
                return this.distributedAdmissionVolumesField;
            }
            set
            {
                this.distributedAdmissionVolumesField = value;
            }
        }

        public uint InstitutionAchievements
        {
            get
            {
                return this.institutionAchievementsField;
            }
            set
            {
                this.institutionAchievementsField = value;
            }
        }

        public uint TargetOrganizations
        {
            get
            {
                return this.targetOrganizationsField;
            }
            set
            {
                this.targetOrganizationsField = value;
            }
        }

        public uint Applications
        {
            get
            {
                return this.applicationsField;
            }
            set
            {
                this.applicationsField = value;
            }
        }

        public uint Orders
        {
            get
            {
                return this.ordersField;
            }
            set
            {
                this.ordersField = value;
            }
        }

        public uint ApplicationsInOrders
        {
            get
            {
                return this.applicationsInOrdersField;
            }
            set
            {
                this.applicationsInOrdersField = value;
            }
        }
    }

    public partial class DeleteResultPackageConflicts
    {

        private List<DeleteResultPackageConflictsApplication> applicationsField;

        private List<uint> competitiveGroupField;

        private List<uint> entranceTestResultsField;

        private List<uint> applicationCommonBenefitsField;

        private List<uint> institutionAchievementsField;

        private List<uint> targetOrganizationsField;

        private List<uint> ordersField;

        private List<DeleteResultPackageConflictsApplication1> applicationsInOrdersField;

        public DeleteResultPackageConflicts()
        {
            this.applicationsInOrdersField = new List<DeleteResultPackageConflictsApplication1>();
            this.ordersField = new List<uint>();
            this.targetOrganizationsField = new List<uint>();
            this.institutionAchievementsField = new List<uint>();
            this.applicationCommonBenefitsField = new List<uint>();
            this.entranceTestResultsField = new List<uint>();
            this.competitiveGroupField = new List<uint>();
            this.applicationsField = new List<DeleteResultPackageConflictsApplication>();
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Application", IsNullable = false)]
        public List<DeleteResultPackageConflictsApplication> Applications
        {
            get
            {
                return this.applicationsField;
            }
            set
            {
                this.applicationsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("CompetitiveGroupID", IsNullable = false)]
        public List<uint> CompetitiveGroup
        {
            get
            {
                return this.competitiveGroupField;
            }
            set
            {
                this.competitiveGroupField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("EntranceTestsResultID", IsNullable = false)]
        public List<uint> EntranceTestResults
        {
            get
            {
                return this.entranceTestResultsField;
            }
            set
            {
                this.entranceTestResultsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("ApplicationCommonBenefitID", IsNullable = false)]
        public List<uint> ApplicationCommonBenefits
        {
            get
            {
                return this.applicationCommonBenefitsField;
            }
            set
            {
                this.applicationCommonBenefitsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("InstitutionAchievementID", IsNullable = false)]
        public List<uint> InstitutionAchievements
        {
            get
            {
                return this.institutionAchievementsField;
            }
            set
            {
                this.institutionAchievementsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("TargetOrganizationID", IsNullable = false)]
        public List<uint> TargetOrganizations
        {
            get
            {
                return this.targetOrganizationsField;
            }
            set
            {
                this.targetOrganizationsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("OrderID", IsNullable = false)]
        public List<uint> Orders
        {
            get
            {
                return this.ordersField;
            }
            set
            {
                this.ordersField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Application", IsNullable = false)]
        public List<DeleteResultPackageConflictsApplication1> ApplicationsInOrders
        {
            get
            {
                return this.applicationsInOrdersField;
            }
            set
            {
                this.applicationsInOrdersField = value;
            }
        }
    }

    public partial class DeleteResultPackageConflictsApplication
    {

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }

    public partial class DeleteResultPackageConflictsApplication1
    {

        private string applicationNumberField;

        private System.DateTime registrationDateField;

        public string ApplicationNumber
        {
            get
            {
                return this.applicationNumberField;
            }
            set
            {
                this.applicationNumberField = value;
            }
        }

        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }
}
